# Import Libraries

In [1]:
import os
import pandas as pd
import networkx as nx
import numpy as np
import random
import pickle

import edge2vec.transition3 as transitions
import edge2vec.edge2vec3 as edge2vec

# Set Seed

In [2]:
seed = None

# Set Parameters

Specify which dataset is used.
*   1 (Original knowledge graph)
*   2 (Restructured knowledge graph)

In [3]:
dataset_nr = 2
assert dataset_nr == 1 or 2

disease_prefix = 'dmd'
assert disease_prefix == 'dmd' or 'hd'

# Additional experiments
NO_GENE_PRODUCTS = 'no gene products'
SINGLE_RELATION_TYPE = 'only one relation type'
RANDOM_FEATURES = 'random node embedding values'
concept_changes = None  # set to None when no conceptual changes are wanted

embedding_method = 'e2v'
    
if concept_changes == NO_GENE_PRODUCTS:
    suffix = '_nogeneprods'
elif concept_changes == SINGLE_RELATION_TYPE:
    suffix = '_singlerel'
elif concept_changes == RANDOM_FEATURES:
    suffix = '_randomfeat'
else:
    suffix = ''

if seed:
    fixed_emb = '_seeded'
else:
    fixed_emb = ''

# Set Folder

In [4]:
curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output', disease_prefix)
dataset_output_dir = os.path.join(curr_output_dir, f'g{dataset_nr}_{embedding_method}{fixed_emb}{suffix}')

if not os.path.exists(dataset_output_dir):
    os.mkdir(dataset_output_dir)
    print(f'Output folder for dataset {dataset_nr} is created: {dataset_output_dir}')
else:
    print(f'Output folder for dataset {dataset_nr} already exists and will be used: {dataset_output_dir}')

Output folder for dataset 2 already exists and will be used: C:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v

In [5]:
def create_run_folder(foldername):
    run_path = os.path.join(dataset_output_dir, foldername)
    os.mkdir(run_path)

    print(f'Output folder for current run on dataset {dataset_nr} is created: {run_path}')
    return run_path

run_folders_list = []

for item in os.listdir(dataset_output_dir):
    curr_path = os.path.join(dataset_output_dir, item)
    if os.path.isdir(curr_path) and 'run' in item:
        run_folders_list.append(item)

if len(run_folders_list) > 0:
    run_folders_list.sort(reverse=True)
    latest_run = run_folders_list[0]
    run_nr_str = latest_run.split('_')[1]

    next_run_nr = int(run_nr_str) + 1
    next_run_folder = 'run_{:03d}'.format(next_run_nr)
    output_path = create_run_folder(next_run_folder)
else:
    first_run_folder = 'run_{:03d}'.format(1)
    output_path = create_run_folder(first_run_folder)

Output folder for current run on dataset 2 is created: C:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v\run_010

# Load Nodes and Edges

In [6]:
nodes = pd.read_csv(f'output/{disease_prefix}/indexed_nodes_{dataset_nr}{suffix}.csv')
nodes

,index_id,id,semantic,label,semantic_id
0,0,ZP:0003032,phenotype,"extension quality, abnormal",8
1,1,MP:0011749,phenotype,perivascular fibrosis,8
2,2,ClinVarVariant:568924,variant,NM_004006.2(DMD):c.7247T>A (p.Leu2416Ter),10
3,3,MP:0002551,phenotype,abnormal blood coagulation,8
4,4,RGD:1305759,gene,Pxn,4
...,...,...,...,...,...
11062,11062,ClinVarVariant:662286,variant,NC_000023.11:g.(?_32614293)_(32651077_?)del,10
11063,11063,MGI:1919517,gene,Lrrc8e,4
11064,11064,ZFIN:ZDB-GENE-030131-2040,gene,actn3b,4
11065,11065,ZP:0005918,phenotype,"brain vasculature broken, abnormal",8
11066,11066,ZP:0021002,phenotype,"sarcomere myotome spatial pattern, abnormal",8

In [7]:
edges = pd.read_csv(f'output/{disease_prefix}/indexed_edges_{dataset_nr}{suffix}.csv')
edges

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
0,ClinVarVariant:526054,NM_004006.2(DMD):c.10224-175_10230del,10,10313,has affected feature,HGNC:2928,DMD,4,6674,0
1,ClinVarVariant:526054,NM_004006.2(DMD):c.10224-175_10230del,10,10313,causes condition,MONDO:0010679,Duchenne muscular dystrophy,2,2191,1
2,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-000322-2,tnnc2,4,2320,2
3,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,in orthology relationship with,ENSEMBL:ENSGALG00000013537,ENSEMBL:ENSGALG00000013537,4,3734,3
4,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-040718-80,tnni2a.3,4,2851,2
...,...,...,...,...,...,...,...,...,...,...
96372,2293,propantheline,3,8037,targets,P11229,Muscarinic acetylcholine receptor M1,5,1258,14
96373,2767,troglitazone,3,10783,targets,P18031,Tyrosine-protein phosphatase non-receptor type 1,5,7624,14
96374,24,phenylbutanoic acid,3,3568,targets,Q92769,Histone deacetylase 2,5,6595,14
96375,2337,quetiapine,3,5478,targets,P11229,Muscarinic acetylcholine receptor M1,5,1258,14
96376,ClinVarVariant:455836,ClinVarVariant:455836,10,8555,causes condition,MONDO:0010679,Duchenne muscular dystrophy,2,2191,1

In [8]:
nodes.loc[nodes['index_id'] == 1840]

,index_id,id,semantic,label,semantic_id
1840,1840,MP:0006403,phenotype,abnormal cochlear endolymph ionic homeostasis,8

In [9]:
edge2vec_df = edges.copy()
edge2vec_df.head(10)

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
0,ClinVarVariant:526054,NM_004006.2(DMD):c.10224-175_10230del,10,10313,has affected feature,HGNC:2928,DMD,4,6674,0
1,ClinVarVariant:526054,NM_004006.2(DMD):c.10224-175_10230del,10,10313,causes condition,MONDO:0010679,Duchenne muscular dystrophy,2,2191,1
2,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-000322-2,tnnc2,4,2320,2
3,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,in orthology relationship with,ENSEMBL:ENSGALG00000013537,ENSEMBL:ENSGALG00000013537,4,3734,3
4,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-040718-80,tnni2a.3,4,2851,2
5,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,causes condition,ZP:0100633,slow muscle cell decreased process quality ske...,8,231,1
6,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,in orthology relationship with,MGI:1890149,Tpm3,4,9334,3
7,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-030520-1,tnnt2c,4,6370,2
8,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-000322-6,mylz3,4,7741,2
9,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-030131-8109,myl1,4,4213,2

# Edge2Vec Embedding Preparation

Initialize edge list with keys 'type' and 'weight'. The 'weight' of each edge is initialized to 1.0.

In [10]:
G = nx.from_pandas_edgelist(edge2vec_df, 'index_head', 'index_tail', 'type', create_using=nx.DiGraph(), edge_key= (('type', int),('id', int)))
G = G.to_undirected()   # for the E2V implementation, use indirected graph
for edge in G.edges():
    G[edge[0]][edge[1]]['weight'] = 1.0
    
for node in G.nodes(data=True):
    print('First node in graph:', node)
    break

for edge in G.edges(data=True):
    print('First edge in graph:', edge)
    break

print('Total number of edges is {}'.format(G.number_of_edges()))
print('Total number of nodes is {}'.format(G.number_of_nodes()))

First node in graph: (10313, {})
First edge in graph: (10313, 6674, {'type': 0, 'weight': 1.0})
Total number of edges is 60668
Total number of nodes is 11067

Count total number of edge types

In [11]:
type_size = len(set(edge2vec_df['type']))
print(f'There are {type_size} edge types')

There are 20 edge types

# Obtain Node Embeddings Using Edge2Vec

Define parameters and generate edge type transition matrix using Edge2Vec EM approach

In [12]:
if disease_prefix == 'hd':
    # Use parameter values obtained with hyperparameter optimization
    if dataset_nr == 1:
        epoch = 10  # number of epochs
        num_walks = 4   # number of walks per node
        walk_length = 5 # length of each walk
        p = 1
        q = 0.5
        
        dim = 64    # desired dimension of the node embedding
        epochs = 10
    else:
        epoch = 10  # number of epochs
        num_walks = 6   # number of walks per node
        walk_length = 7 # length of each walk
        p = 0.75
        q = 1
        
        dim = 64
        epochs = 10
else:
    if dataset_nr == 1:
        epoch = 10  # number of epochs
        num_walks = 2   # number of walks per node
        walk_length = 7 # length of each walk
        p = 0.70
        q = 1
        
        dim = 32    # desired dimension of the node embedding
        epochs = 10
    else:
        epoch = 5  # number of epochs
        num_walks = 6   # number of walks per node
        walk_length = 7 # length of each walk
        p = 0.75
        q = 1
        
        dim = 64    # desired dimension of the node embedding
        epochs = 10
    
directed = True
e_step = 3

print(num_walks, walk_length, dim, p, q, epoch)

6 7 64 0.75 1 5

In [13]:
def get_e2v_embeddings(save=False):
    print('Initializing transition matrix...')
    M = transitions.initialize_edge_type_matrix(type_size)

    print('Updating transition matrix...')
    for i in range(epoch):
        walks = transitions.simulate_walks_1(G, num_walks, walk_length, M, directed, p, q, seed) # M step
        print(f'{i}th iteration of updating matrix')
        M = transitions.update_trans_matrix(walks, type_size, e_step) # E step

    print("Finished generating values for transition matrix!")
    
    print('Overview of resulting edge type transition matrix (float values have been truncated to fit the view!):')
    print('\n'.join(['\t'.join([str(cell)[:5] for cell in row]) for row in M]))
    
    if save:
        # Save transition matrix
        np.save(f'{output_path}/transitionmatrix_{dataset_nr}.npy', M)
    
    print('Generate walks constrained by edge type transition matrix...')
    walks = edge2vec.simulate_walks_2(G, num_walks, walk_length, M, p, q, seed)
    
    # Generate node embeddings using Word2Vec (skip-gram model) with as input the generated walks 
    window_size = walk_length - 1   # maximum distance between predicted and context node
    workers = 8 # threads used

    w2v_model = edge2vec.Word2Vec(walks, vector_size=dim, window=window_size, min_count=0, sg=1, workers=workers, epochs=epochs, seed=seed)
    
    word_vectors = w2v_model.wv
    if save:
        word_vectors.save(f'{output_path}/w2v_{dataset_nr}.dvectors')
        
    e2v_embedding = pd.DataFrame(columns = ['Node', 'Embedding'])
    e2v_embedding_list = []
    for _, key in enumerate(w2v_model.wv.index_to_key):
        e2v_embedding.loc[int(key)] = pd.Series({'Node':int(key), 'Embedding':list(w2v_model.wv[key])})
        e2v_embedding_list.append(list(w2v_model.wv[key]))
        
    e2v_embedding = e2v_embedding.sort_values('Node')
    
    return M, e2v_embedding, e2v_embedding_list

In [14]:
if concept_changes == RANDOM_FEATURES:
    random.seed(111)
    nodes_total = len(G.nodes)
    random_feats = pd.DataFrame(index=range(nodes_total), columns=['Node', 'Embedding'])
    random_feats['Node'] = random_feats.index
    
    random_emb_nodes = []
    for _ in range(nodes_total):
        random_emb = []
        for _ in range(dim):
            random_emb.append(random.uniform(-0.5, 0.5))
        random_emb_nodes.append(random_emb)
        
    random_feats['Embedding'] = random_emb_nodes
    
    with open(f'{output_path}/random_node_embeddings_{dataset_nr}.pkl', 'wb') as f:
        pickle.dump(random_feats, f)
else:
    get_e2v_embeddings(save=True)

Initializing transition matrix...
Updating transition matrix...
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
0th iteration of updating matrix
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
1th iteration of updating matrix
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
2th iteration of updating matrix
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
3th iteration of updating matrix
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
4th iteration of updating matrix
Finished generating values for transition matrix!
Overview of resulting edge type transition matrix (float values have been truncated to fit the view!):
0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	0.5
1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5
1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5
1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5
1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5
1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5
1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	0.5
0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	0.5
0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5
Generate walks constrained by edge type transition matrix...
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6

## Check embedding similarities

In [15]:
#transition_M_1, e2v_embedding_1_df, e2v_embedding_1_list = get_e2v_embeddings()
#transition_M_2, e2v_embedding_2_df, e2v_embedding_2_list = get_e2v_embeddings()

In [16]:
#from sklearn.metrics.pairwise import cosine_similarity

#similarity_matrix = cosine_similarity(e2v_embedding_1_list, e2v_embedding_2_list)

#cos_similarities = []
#for node in G.nodes():
#    cos_similarities.append(similarity_matrix[node][node])

In [17]:
#cos_similarities