# Import Libraries

In [1]:
import os
import pandas as pd
import networkx as nx
import numpy as np
import random
import pickle

import edge2vec.transition3 as transitions
import edge2vec.edge2vec3 as edge2vec

# Set Seed

In [2]:
seed = None

# Set Parameters

Specify which dataset is used.
*   1 (Original knowledge graph)
*   2 (Restructured knowledge graph)

In [3]:
dataset_nr = 2
assert dataset_nr == 1 or 2

disease_prefix = 'hd'
assert disease_prefix == 'dmd' or 'hd'

# Additional experiments
NO_GENE_PRODUCTS = 'no gene products'
SINGLE_RELATION_TYPE = 'only one relation type'
RANDOM_FEATURES = 'random node embedding values'
concept_changes = None  # set to None when no conceptual changes are wanted

embedding_method = 'e2v'
    
if concept_changes == NO_GENE_PRODUCTS:
    suffix = '_nogeneprods'
elif concept_changes == SINGLE_RELATION_TYPE:
    suffix = '_singlerel'
elif concept_changes == RANDOM_FEATURES:
    suffix = '_randomfeat'
else:
    suffix = ''

if seed:
    fixed_emb = '_seeded'
else:
    fixed_emb = ''

# Set Folder

In [4]:
curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output', disease_prefix)
dataset_output_dir = os.path.join(curr_output_dir, f'g{dataset_nr}_{embedding_method}{fixed_emb}{suffix}')

if not os.path.exists(dataset_output_dir):
    os.mkdir(dataset_output_dir)
    print(f'Output folder for dataset {dataset_nr} is created: {dataset_output_dir}')
else:
    print(f'Output folder for dataset {dataset_nr} already exists and will be used: {dataset_output_dir}')

Output folder for dataset 1 already exists and will be used: C:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v

In [5]:
def create_run_folder(foldername):
    run_path = os.path.join(dataset_output_dir, foldername)
    os.mkdir(run_path)

    print(f'Output folder for current run on dataset {dataset_nr} is created: {run_path}')
    return run_path

run_folders_list = []

for item in os.listdir(dataset_output_dir):
    curr_path = os.path.join(dataset_output_dir, item)
    if os.path.isdir(curr_path) and 'run' in item:
        run_folders_list.append(item)

if len(run_folders_list) > 0:
    run_folders_list.sort(reverse=True)
    latest_run = run_folders_list[0]
    run_nr_str = latest_run.split('_')[1]

    next_run_nr = int(run_nr_str) + 1
    next_run_folder = 'run_{:03d}'.format(next_run_nr)
    output_path = create_run_folder(next_run_folder)
else:
    first_run_folder = 'run_{:03d}'.format(1)
    output_path = create_run_folder(first_run_folder)

Output folder for current run on dataset 1 is created: C:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v\run_010

# Load Nodes and Edges

In [6]:
nodes = pd.read_csv(f'output/{disease_prefix}/indexed_nodes_{dataset_nr}{suffix}.csv')
nodes

,index_id,id,semantic,label,semantic_id
0,0,ENSEMBL:ENSCAFG00000047980,ORTH,ENSEMBL:ENSCAFG00000047980,5
1,1,ENSEMBL:ENSFCAG00000005686,ORTH,ENSEMBL:ENSFCAG00000005686,5
2,2,NCBIGene:110438919,GENE,LOC110438919,3
3,3,ENSEMBL:ENSBTAG00000000219,ORTH,ENSEMBL:ENSBTAG00000000219,5
4,4,ZFIN:ZDB-GENE-040426-1961,ORTH,dynll1,5
...,...,...,...,...,...
14828,14828,HP:0000054,DISO,Micropenis,1
14829,14829,HGNC:7734,GENE,NEFM,3
14830,14830,ENSEMBL:ENSBTAG00000003758,ORTH,TKT,5
14831,14831,WBPhenotype:0001889,DISO,body wall muscle sarcomere morphology variant,1
14832,14832,WBPhenotype:0001172,DISO,programmed cell death variant,1

In [7]:
edges = pd.read_csv(f'output/{disease_prefix}/indexed_edges_{dataset_nr}{suffix}.csv')
edges

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
0,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,ENSEMBL:ENSSSCG00000040510,KIF9,5,1827,0
1,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,ENSEMBL:ENSCAFG00000013358,ENSEMBL:ENSCAFG00000013358,5,12004,0
2,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,Xenbase:XB-GENE-995481,kif9,5,11336,0
3,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,HGNC:16666,KIF9,3,13100,0
4,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,ZFIN:ZDB-GENE-160728-129,kif9,5,5001,0
...,...,...,...,...,...,...,...,...,...,...
228994,2491,sufentanil,2,1243,targets,HGNC:8156,OPRM1,3,9620,15
228995,Coriell:GM04198,NIGMS-GM04198,4,4421,has role in modeling,MONDO:0007739,Huntington disease,1,6883,8
228996,1690,pethidine,2,823,targets,HGNC:8156,OPRM1,3,9620,15
228997,Coriell:GM04818,NIGMS-GM04818,4,9339,has role in modeling,MONDO:0007739,Huntington disease,1,6883,8
228998,3535,rutoside,2,1699,targets,HGNC:29079,KDM1A,3,10737,15

In [8]:
nodes.loc[nodes['index_id'] == 1840]

      index_id          id semantic                      label  semantic_id
1840      1840  ZP:0001024     DISO  lens protruding, abnormal            1

In [9]:
edge2vec_df = edges.copy()
edge2vec_df.head(10)

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
0,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,ENSEMBL:ENSSSCG00000040510,KIF9,5,1827,0
1,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,ENSEMBL:ENSCAFG00000013358,ENSEMBL:ENSCAFG00000013358,5,12004,0
2,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,Xenbase:XB-GENE-995481,kif9,5,11336,0
3,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,HGNC:16666,KIF9,3,13100,0
4,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,ZFIN:ZDB-GENE-160728-129,kif9,5,5001,0
5,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,RGD:1565187,Kif9,5,5568,0
6,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,ENSEMBL:ENSGALG00000005517,KIF9,5,6688,0
7,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,MGI:1098237,Kif9,5,12813,0
8,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,ENSEMBL:ENSECAG00000025122,ENSEMBL:ENSECAG00000025122,5,14123,0
9,ENSEMBL:ENSGALG00000003916,ENSEMBL:ENSGALG00000003916,5,7439,in 1 to 1 orthology relationship with,Xenbase:XB-GENE-1014415,siah1,5,514,0

# Edge2Vec Embedding Preparation

Initialize edge list with keys 'type' and 'weight'. The 'weight' of each edge is initialized to 1.0.

In [10]:
G = nx.from_pandas_edgelist(edge2vec_df, 'index_head', 'index_tail', 'type', create_using=nx.DiGraph(), edge_key= (('type', int),('id', int)))
G = G.to_undirected()   # for the E2V implementation, use indirected graph
for edge in G.edges():
    G[edge[0]][edge[1]]['weight'] = 1.0
    
for node in G.nodes(data=True):
    print('First node in graph:', node)
    break

for edge in G.edges(data=True):
    print('First edge in graph:', edge)
    break

print('Total number of edges is {}'.format(G.number_of_edges()))
print('Total number of nodes is {}'.format(G.number_of_nodes()))

First node in graph: (997, {})
First edge in graph: (997, 1827, {'type': 0, 'weight': 1.0})
Total number of edges is 134749
Total number of nodes is 14833

Count total number of edge types

In [11]:
type_size = len(set(edge2vec_df['type']))
print(f'There are {type_size} edge types')

There are 22 edge types

# Obtain Node Embeddings Using Edge2Vec

Define parameters and generate edge type transition matrix using Edge2Vec EM approach

In [12]:
if disease_prefix == 'hd':
    # Use parameter values obtained with hyperparameter optimization
    if dataset_nr == 1:
        epoch = 10  # number of epochs
        num_walks = 6   # number of walks per node
        walk_length = 5 # length of each walk
        p = 0.75
        q = 0.5
        
        dim = 32    # desired dimension of the node embedding
        epochs = 10
    else:
        epoch = 10  # number of epochs
        num_walks = 6   # number of walks per node
        walk_length = 5 # length of each walk
        p = 0.5
        q = 1
        
        dim = 128
        epochs = 10
else:
    if dataset_nr == 1:
        epoch = 10  # number of epochs
        num_walks = 2   # number of walks per node
        walk_length = 7 # length of each walk
        p = 0.70
        q = 1
        
        dim = 32    # desired dimension of the node embedding
        epochs = 10
    else:
        epoch = 5  # number of epochs
        num_walks = 6   # number of walks per node
        walk_length = 7 # length of each walk
        p = 0.75
        q = 1
        
        dim = 64    # desired dimension of the node embedding
        epochs = 10
    
directed = True
e_step = 3

print(num_walks, walk_length, dim, p, q, epoch)

6 5 32 0.75 0.5 10

In [13]:
def get_e2v_embeddings(save=False):
    print('Initializing transition matrix...')
    M = transitions.initialize_edge_type_matrix(type_size)

    print('Updating transition matrix...')
    for i in range(epoch):
        walks = transitions.simulate_walks_1(G, num_walks, walk_length, M, directed, p, q, seed) # M step
        print(f'{i}th iteration of updating matrix')
        M = transitions.update_trans_matrix(walks, type_size, e_step) # E step

    print("Finished generating values for transition matrix!")
    
    print('Overview of resulting edge type transition matrix (float values have been truncated to fit the view!):')
    print('\n'.join(['\t'.join([str(cell)[:5] for cell in row]) for row in M]))
    
    if save:
        # Save transition matrix
        np.save(f'{output_path}/transitionmatrix_{dataset_nr}.npy', M)
    
    print('Generate walks constrained by edge type transition matrix...')
    walks = edge2vec.simulate_walks_2(G, num_walks, walk_length, M, p, q, seed)
    
    # Generate node embeddings using Word2Vec (skip-gram model) with as input the generated walks 
    window_size = walk_length - 1   # maximum distance between predicted and context node
    workers = 8 # threads used

    w2v_model = edge2vec.Word2Vec(walks, vector_size=dim, window=window_size, min_count=0, sg=1, workers=workers, epochs=epochs, seed=seed)
    
    word_vectors = w2v_model.wv
    if save:
        word_vectors.save(f'{output_path}/w2v_{dataset_nr}.dvectors')
        
    e2v_embedding = pd.DataFrame(columns = ['Node', 'Embedding'])
    e2v_embedding_list = []
    for _, key in enumerate(w2v_model.wv.index_to_key):
        e2v_embedding.loc[int(key)] = pd.Series({'Node':int(key), 'Embedding':list(w2v_model.wv[key])})
        e2v_embedding_list.append(list(w2v_model.wv[key]))
        
    e2v_embedding = e2v_embedding.sort_values('Node')
    
    return M, e2v_embedding, e2v_embedding_list

In [14]:
if concept_changes == RANDOM_FEATURES:
    random.seed(111)
    nodes_total = len(G.nodes)
    random_feats = pd.DataFrame(index=range(nodes_total), columns=['Node', 'Embedding'])
    random_feats['Node'] = random_feats.index
    
    random_emb_nodes = []
    for _ in range(nodes_total):
        random_emb = []
        for _ in range(dim):
            random_emb.append(random.uniform(-0.5, 0.5))
        random_emb_nodes.append(random_emb)
        
    random_feats['Embedding'] = random_emb_nodes
    
    with open(f'{output_path}/random_node_embeddings_{dataset_nr}.pkl', 'wb') as f:
        pickle.dump(random_feats, f)
else:
    get_e2v_embeddings(save=True)

Initializing transition matrix...
Updating transition matrix...
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
0th iteration of updating matrix

c:\Users\rosa-\anaconda3\envs\xaifo\lib\site-packages\scipy\stats\_morestats.py:3428: UserWarning: Sample size too small for normal approximation.
  warnings.warn("Sample size too small for normal approximation.")

Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
1th iteration of updating matrix
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
2th iteration of updating matrix
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
3th iteration of updating matrix
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
4th iteration of updating matrix
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
5th iteration of updating matrix
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
6th iteration of updating matrix
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
7th iteration of updating matrix
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
8th iteration of updating matrix
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6
9th iteration of updating matrix
Finished generating values for transition matrix!
Overview of resulting edge type transition matrix (float values have been truncated to fit the view!):
0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	0.5	0.5	1.0	1.0	1.0	0.5	1.0	0.5	0.5	0.5	0.5
1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	0.5	0.5	1.0	1.0	1.0	0.5	1.0	0.5	0.5	0.5	0.5
1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	0.5	0.5	1.0	1.0	1.0	0.5	1.0	0.5	0.5	0.5	0.5
1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	1.0	0.5	0.5	0.5	1.0	1.0	1.0	0.5	1.0	0.5	0.5	0.5	0.5
1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	1.0	0.5	0.5	0.5	1.0	1.0	1.0	0.5	1.0	0.5	0.5	0.5	0.5
1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	1.0	0.5	0.5	0.5	1.0	1.0	1.0	0.5	1.0	0.5	0.5	0.5	0.5
1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	1.0	0.5	0.5	0.5	1.0	1.0	1.0	0.5	1.0	0.5	0.5	0.5	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	1.0	0.5	0.5	0.5	1.0	1.0	1.0	0.5	1.0	0.5	0.5	0.5	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	1.0	0.5	0.5	0.5	1.0	1.0	1.0	0.5	1.0	0.5	0.5	0.5	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	0.5	0.5	0.5	1.0	1.0	1.0	0.5	1.0	0.5	0.5	0.5	0.5
0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5
0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5
0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	0.5	0.5	0.5	0.999	1.0	0.5	1.0	0.5	0.5	0.5	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	0.5	0.5	0.999	0.5	1.0	0.5	1.0	0.5	0.5	0.5	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	0.5	0.5	1.0	1.0	0.5	0.5	1.0	0.5	0.5	0.5	0.5
0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5
1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	0.5	0.5	0.5	1.0	1.0	1.0	0.5	0.5	0.5	0.5	0.5	0.5
0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5
0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5
0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5
0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5
Generate walks constrained by edge type transition matrix...
Walk iteration:
1 / 6
2 / 6
3 / 6
4 / 6
5 / 6
6 / 6

## Check embedding similarities

In [15]:
#transition_M_1, e2v_embedding_1_df, e2v_embedding_1_list = get_e2v_embeddings()
#transition_M_2, e2v_embedding_2_df, e2v_embedding_2_list = get_e2v_embeddings()

In [16]:
#from sklearn.metrics.pairwise import cosine_similarity

#similarity_matrix = cosine_similarity(e2v_embedding_1_list, e2v_embedding_2_list)

#cos_similarities = []
#for node in G.nodes():
#    cos_similarities.append(similarity_matrix[node][node])

In [17]:
#cos_similarities