This notebook loads all edges and nodes of the relevant knowledge graph. New dataframes are created for the nodes and edges including index values for each node.

# Import Libraries

In [19]:
import pandas as pd

# Set Parameters

Specify which dataset is used.
*   1 (Original knowledge graph)
*   2 (Restructured knowledge graph)

In [20]:
dataset_nr = 2
assert dataset_nr == 1 or 2

NO_GENE_PRODUCTS = 'no gene products'
SINGLE_RELATION_TYPE = 'only one relation type'
RANDOM_FEATURES = 'random node embedding values'
concept_changes = ''

dataset_prefix = 'dmd'

if dataset_nr == 1:
    prefix = 'prev'
    date_str = '2024-07-19'
else:
    prefix = 'restr'
    date_str = '2024-07-19'
    
if concept_changes == NO_GENE_PRODUCTS:
    suffix = '_nogeneprods'
elif concept_changes == SINGLE_RELATION_TYPE:
    suffix = '_singlerel'
elif concept_changes == RANDOM_FEATURES:
    suffix = '_randomfeat'
else:
    suffix = ''
    
FILE_EDGES = f'{prefix}_{dataset_prefix}_kg_edges_{date_str}.csv'
FILE_NODES = f'{prefix}_{dataset_prefix}_kg_nodes_{date_str}.csv'

# Load Edges

Load all edges of knowledge graph

In [21]:
edges = pd.read_csv(f'output/{dataset_prefix}/{FILE_EDGES}', header=0)
edges.head(10)

,id,subject,object,relation_id,relation_label,relation_iri
0,7723b5637752a00987ff38abfe395448,ClinVarVariant:526054,HGNC:2928,GENO:0000418,has affected feature,NaN
1,e05a8f6f62b103d30f11bbc24c3b0fa3,ZFIN:ZDB-GENE-030826-16,ZFIN:ZDB-GENE-000322-2,RO:0002434,interacts with,NaN
2,045daaad50524040cf0ec21666d4ba32,ZFIN:ZDB-GENE-030826-16,ENSEMBL:ENSGALG00000013537,RO:HOM0000017,in orthology relationship with,NaN
3,991a02cacbfc53eb7bf059f3424a1779,SGD:S000001532,MONARCH:APO_0000197APO_0000004,RO:0003303,causes condition,http://purl.obolibrary.org/obo/RO_0003303
4,8b5faf8e2a7c7b06cbc3924bdae3d34c,HGNC:3057,FlyBase:FBgn0033739,RO:HOM0000017,in orthology relationship with,http://purl.obolibrary.org/obo/RO_HOM0000017
5,8580aeea85e0af17ae9de495538d996a,HGNC:6493,HP:0000670,RO:0003303,causes condition,http://purl.obolibrary.org/obo/RO_0003303
6,4ff1ecf115d5a562648897e6d32cc0aa,HGNC:583,HP:0002900,RO:0003303,causes condition,http://purl.obolibrary.org/obo/RO_0003303
7,9709f14e869fa609ada2640101a362c0,MONDO:0010542,REACT:R-HSA-3000171,RO:0002331,involved in,NaN
8,32a8e8c741ae45efd1a2a46dff92046b,MGI:1355285,MGI:94885,RO:0002434,interacts with,NaN
9,2199786e918a155d7aa32829604e381e,ENSEMBL:ENSCAFG00000004208,ENSEMBL:ENSMODG00000023714,RO:HOM0000017,in orthology relationship with,http://purl.obolibrary.org/obo/RO_HOM0000017

Extract the relevant columns and rename them

In [22]:
edges = edges[['subject', 'relation_label', 'object']]
edges.rename(columns={'subject': 'head', 'relation_label': 'relation', 'object': 'tail'}, inplace=True)
edges.head(10)

,head,relation,tail
0,ClinVarVariant:526054,has affected feature,HGNC:2928
1,ZFIN:ZDB-GENE-030826-16,interacts with,ZFIN:ZDB-GENE-000322-2
2,ZFIN:ZDB-GENE-030826-16,in orthology relationship with,ENSEMBL:ENSGALG00000013537
3,SGD:S000001532,causes condition,MONARCH:APO_0000197APO_0000004
4,HGNC:3057,in orthology relationship with,FlyBase:FBgn0033739
5,HGNC:6493,causes condition,HP:0000670
6,HGNC:583,causes condition,HP:0002900
7,MONDO:0010542,involved in,REACT:R-HSA-3000171
8,MGI:1355285,interacts with,MGI:94885
9,ENSEMBL:ENSCAFG00000004208,in orthology relationship with,ENSEMBL:ENSMODG00000023714

In [23]:
def convert_to_int_str(value):
    try:
        return str(int(float(value)))
    except ValueError:
        return value

edges['head'] = edges['head'].apply(convert_to_int_str)
edges['tail'] = edges['tail'].apply(convert_to_int_str)

In [24]:
print(f'There are {edges.shape[0]} edges')

There are 96377 edges

# Load Nodes

Load all nodes of knowledge graph

In [25]:
nodes = pd.read_csv(f'output/{dataset_prefix}/{FILE_NODES}', header=0)
nodes['index_id'] = nodes.index
nodes.head(10)

,id,label,iri,semantic,index_id
0,ZP:0003032,"extension quality, abnormal",NaN,phenotype,0
1,MP:0011749,perivascular fibrosis,NaN,phenotype,1
2,ClinVarVariant:568924,NM_004006.2(DMD):c.7247T>A (p.Leu2416Ter),NaN,variant,2
3,MP:0002551,abnormal blood coagulation,NaN,phenotype,3
4,RGD:1305759,Pxn,NaN,gene,4
5,ZFIN:ZDB-GENE-090312-131,tmod1,NaN,gene,5
6,Coriell:GM23086,NIGMS-GM23086,NaN,biological artifact,6
7,FBcv:0000718,decreased cell growth,NaN,phenotype,7
8,ENSEMBL:ENSGALG00000013968,ENSEMBL:ENSGALG00000013968,NaN,gene,8
9,ENSEMBL:ENSACAG00000010643,ENSEMBL:ENSACAG00000010643,NaN,gene,9

Extract relevant columns

In [26]:
nodes = nodes[['index_id', 'id', 'semantic', 'label']]
nodes.head(10)

,index_id,id,semantic,label
0,0,ZP:0003032,phenotype,"extension quality, abnormal"
1,1,MP:0011749,phenotype,perivascular fibrosis
2,2,ClinVarVariant:568924,variant,NM_004006.2(DMD):c.7247T>A (p.Leu2416Ter)
3,3,MP:0002551,phenotype,abnormal blood coagulation
4,4,RGD:1305759,gene,Pxn
5,5,ZFIN:ZDB-GENE-090312-131,gene,tmod1
6,6,Coriell:GM23086,biological artifact,NIGMS-GM23086
7,7,FBcv:0000718,phenotype,decreased cell growth
8,8,ENSEMBL:ENSGALG00000013968,gene,ENSEMBL:ENSGALG00000013968
9,9,ENSEMBL:ENSACAG00000010643,gene,ENSEMBL:ENSACAG00000010643

In [27]:
print(f'There are {nodes.shape[0]} nodes')

There are 11067 nodes

Convert semantic groups from categorical to numerical values (`semantic_id`)

In [28]:
nodes['semantic'] = nodes['semantic'].astype('category')
nodes['semantic_id'] = nodes['semantic'].cat.codes
nodes.head(10)

,index_id,id,semantic,label,semantic_id
0,0,ZP:0003032,phenotype,"extension quality, abnormal",8
1,1,MP:0011749,phenotype,perivascular fibrosis,8
2,2,ClinVarVariant:568924,variant,NM_004006.2(DMD):c.7247T>A (p.Leu2416Ter),10
3,3,MP:0002551,phenotype,abnormal blood coagulation,8
4,4,RGD:1305759,gene,Pxn,4
5,5,ZFIN:ZDB-GENE-090312-131,gene,tmod1,4
6,6,Coriell:GM23086,biological artifact,NIGMS-GM23086,0
7,7,FBcv:0000718,phenotype,decreased cell growth,8
8,8,ENSEMBL:ENSGALG00000013968,gene,ENSEMBL:ENSGALG00000013968,4
9,9,ENSEMBL:ENSACAG00000010643,gene,ENSEMBL:ENSACAG00000010643,4

Create a dictionary that can be used as mapping between `semantic_id` and `semantic`

In [29]:
node_semantic_dict = dict(enumerate(nodes['semantic'].cat.categories))
node_semantic_dict

{0: 'biological artifact',
 1: 'biological process',
 2: 'disease',
 3: 'drug',
 4: 'gene',
 5: 'gene product',
 6: 'genotype',
 7: 'molecular function',
 8: 'phenotype',
 9: 'taxon',
 10: 'variant'}

Save new dataframe containing all nodes into csv file

In [30]:
nodes.to_csv(f'output/{dataset_prefix}/indexed_nodes_{dataset_nr}{suffix}.csv', index=False)

# Joining Dataframes

Merge dataframes with nodes and edges in order to join semantic classes and indices of nodes with heads and tails of the edges.

In [31]:
kg_df = pd.merge(edges, nodes,
                 left_on='head', right_on='id',
                 how='inner')
kg_df = kg_df[['head', 'label', 'semantic_id', 'index_id', 'relation', 'tail']]
kg_df.rename(columns={'label': 'label_head', 'semantic_id': 'class_head', 'index_id': 'index_head'}, inplace=True)
kg_df.head(10)

,head,label_head,class_head,index_head,relation,tail
0,ClinVarVariant:526054,NM_004006.2(DMD):c.10224-175_10230del,10,10313,has affected feature,HGNC:2928
1,ClinVarVariant:526054,NM_004006.2(DMD):c.10224-175_10230del,10,10313,causes condition,MONDO:0010679
2,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-000322-2
3,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,in orthology relationship with,ENSEMBL:ENSGALG00000013537
4,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-040718-80
5,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,causes condition,ZP:0100633
6,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,in orthology relationship with,MGI:1890149
7,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-030520-1
8,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-000322-6
9,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-030131-8109

In [32]:
kg_df = pd.merge(kg_df, nodes,
                 left_on='tail', right_on='id',
                 how='left')
kg_df = kg_df[['head', 'label_head', 'class_head', 'index_head', 'relation', 'tail', 'label', 'semantic_id', 'index_id']]
kg_df.rename(columns={'label': 'label_tail', 'semantic_id': 'class_tail', 'index_id': 'index_tail'}, inplace=True)
kg_df.head(10)

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail
0,ClinVarVariant:526054,NM_004006.2(DMD):c.10224-175_10230del,10,10313,has affected feature,HGNC:2928,DMD,4,6674
1,ClinVarVariant:526054,NM_004006.2(DMD):c.10224-175_10230del,10,10313,causes condition,MONDO:0010679,Duchenne muscular dystrophy,2,2191
2,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-000322-2,tnnc2,4,2320
3,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,in orthology relationship with,ENSEMBL:ENSGALG00000013537,ENSEMBL:ENSGALG00000013537,4,3734
4,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-040718-80,tnni2a.3,4,2851
5,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,causes condition,ZP:0100633,slow muscle cell decreased process quality ske...,8,231
6,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,in orthology relationship with,MGI:1890149,Tpm3,4,9334
7,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-030520-1,tnnt2c,4,6370
8,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-000322-6,mylz3,4,7741
9,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-030131-8109,myl1,4,4213

Encode string values of relation labels as numeric values.

In [33]:
kg_df['type'], relation_labels = pd.factorize(kg_df['relation'])
kg_df.head(10)

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
0,ClinVarVariant:526054,NM_004006.2(DMD):c.10224-175_10230del,10,10313,has affected feature,HGNC:2928,DMD,4,6674,0
1,ClinVarVariant:526054,NM_004006.2(DMD):c.10224-175_10230del,10,10313,causes condition,MONDO:0010679,Duchenne muscular dystrophy,2,2191,1
2,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-000322-2,tnnc2,4,2320,2
3,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,in orthology relationship with,ENSEMBL:ENSGALG00000013537,ENSEMBL:ENSGALG00000013537,4,3734,3
4,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-040718-80,tnni2a.3,4,2851,2
5,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,causes condition,ZP:0100633,slow muscle cell decreased process quality ske...,8,231,1
6,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,in orthology relationship with,MGI:1890149,Tpm3,4,9334,3
7,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-030520-1,tnnt2c,4,6370,2
8,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-000322-6,mylz3,4,7741,2
9,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-030131-8109,myl1,4,4213,2

In [34]:
relation_labels

Index(['has affected feature', 'causes condition', 'interacts with',
       'in orthology relationship with', 'found in', 'enables',
       'contributes to condition', 'involved in', 'associated with phenotype',
       'colocalizes with', 'likely causes condition', 'expresses gene',
       'has role in modeling', 'is substance that treats', 'targets',
       'is allele of', 'is variant in', 'is of', 'has genotype',
       'is product of'],
      dtype='object')

Save new dataframe containing all edges into csv file

In [35]:
if concept_changes == NO_GENE_PRODUCTS and dataset_nr == 2:
    all_edges = kg_df.copy()
    
    all_gene_products = all_edges.loc[all_edges['type'] == list(relation_labels).index('is product of')]
    all_targeting_drugs = all_edges.loc[all_edges['type'] == list(relation_labels).index('targets')]
    
    merged_df = pd.merge(all_targeting_drugs, all_gene_products, how='left', left_on='tail', right_on='head', indicator=True)
    result_df = merged_df[merged_df['_merge'] == 'both']
    
    new_edges = result_df[['head_x', 'label_head_x', 'class_head_x', 'index_head_x', 'relation_x', 'tail_y', 'label_tail_y', 'class_tail_y', 'index_tail_y', 'type_y']]
    drug_gene_edges = new_edges.rename(columns={'head_x': 'head', 'label_head_x': 'label_head', 'class_head_x': 'class_head', 'index_head_x': 'index_head', 
                                                'relation_x': 'relation', 'tail_y': 'tail', 'label_tail_y': 'label_tail', 'class_tail_y': 'class_tail', 'index_tail_y': 'index_tail', 'type_y': 'type'})
    
    
    all_non_gene_products = all_edges.loc[(all_edges['type'] != list(relation_labels).index('is product of')) & (all_edges['type'] != list(relation_labels).index('targets'))]
    all_new_edges = pd.concat([all_non_gene_products, drug_gene_edges], ignore_index=True)

    gene_products_nodes = nodes.loc[nodes['semantic'] == 'gene product']
    no_gene_products_nodes = nodes.loc[nodes['semantic'] != 'gene product']
    no_gene_products_nodes.reset_index(inplace=True)
    no_gene_products_nodes['index_id'] = no_gene_products_nodes.index
    
    # Remap indices of head and tail of edges with node indices
    reindexed_left = pd.merge(all_new_edges, no_gene_products_nodes, how='inner', left_on='index_head', right_on='index')[['head', 'label_head', 'class_head', 'index_id', 
                                                                                                                           'relation', 
                                                                                                                           'tail', 'label_tail', 'class_tail', 'index_tail', 'type']]
    reindexed_left.rename(columns={'index_id': 'index_head'}, inplace=True)
    reindexed_left_right = pd.merge(reindexed_left, no_gene_products_nodes, how='inner', left_on='index_tail', right_on='index')[['head', 'label_head', 'class_head', 'index_head', 
                                                                                                                                  'relation', 
                                                                                                                                  'tail', 'label_tail', 'class_tail', 'index_id', 'type']]
    reindexed_left_right.rename(columns={'index_id': 'index_tail'}, inplace=True)
    
    no_gene_products_nodes.drop(['index'], axis=1, inplace=True)
    
    # Remap relation type indices
    reindexed_left_right['type'], relation_labels_new = pd.factorize(reindexed_left_right['relation'])
    
    # Remap node type indices
    no_gene_products_nodes['semantic_id'] = no_gene_products_nodes['semantic'].cat.codes
    
    print(f'There are {nodes.shape[0]} nodes in total before change')
    print(f'There are {no_gene_products_nodes.shape[0]} nodes after change')
    print(f'There are {gene_products_nodes.shape[0]} gene product nodes removed after change')

    print(f'There are {kg_df.shape[0]} edges in total before change')
    print(f'There are {reindexed_left_right.shape[0]} edges after change')
    print(f'There are {all_gene_products.shape[0]} gene product related rows removed after change')
    
    print(f'Changed from {len(relation_labels)} types of relations to {len(relation_labels_new)} types of relations.')
    print(f"Changed from {len(node_semantic_dict)} types of nodes to {no_gene_products_nodes['semantic_id'].nunique()} nodes.")
    
elif concept_changes == SINGLE_RELATION_TYPE:
    all_edges = kg_df.copy()
    all_edges['relation'] = 'edge'
    all_edges['type'], relation_labels_new = pd.factorize(all_edges['relation'])

    print(f'There are {kg_df.shape[0]} edges in total before change')
    print(f'There are {all_edges.shape[0]} edges after change')
    
    print(f'Changed from {len(relation_labels)} types of relations to {len(relation_labels_new)} types of relations.')
    print(f"Changed from {len(node_semantic_dict)} types of nodes to {nodes['semantic_id'].nunique()} nodes.")

In [36]:
if concept_changes == NO_GENE_PRODUCTS and dataset_nr == 2:
    reindexed_left_right.to_csv(f'output/{dataset_prefix}/indexed_edges_{dataset_nr}{suffix}.csv', index=False)
    no_gene_products_nodes.to_csv(f'output/{dataset_prefix}/indexed_nodes_{dataset_nr}{suffix}.csv', index=False)
    
elif concept_changes == SINGLE_RELATION_TYPE:
    all_edges.to_csv(f'output/{dataset_prefix}/indexed_edges_{dataset_nr}{suffix}.csv', index=False)
    
else:
    kg_df.to_csv(f'output/{dataset_prefix}/indexed_edges_{dataset_nr}{suffix}.csv', index=False)