This notebook loads all edges and nodes of the relevant knowledge graph. New dataframes are created for the nodes and edges including index values for each node.

# Import Libraries

In [1]:
import pandas as pd

# Set Parameters

Specify which dataset is used.
*   1 (Original knowledge graph)
*   2 (Restructured knowledge graph)

In [2]:
dataset_nr = 1
assert dataset_nr == 1 or 2

NO_GENE_PRODUCTS = 'no gene products'
SINGLE_RELATION_TYPE = 'only one relation type'
RANDOM_FEATURES = 'random node embedding values'
concept_changes = ''

dataset_prefix = 'hd'

if dataset_nr == 1:
    prefix = 'prev'
    date_str = '2024-07-09'
else:
    prefix = 'restr'
    date_str = '2024-07-10'
    
if concept_changes == NO_GENE_PRODUCTS:
    suffix = '_nogeneprods'
elif concept_changes == SINGLE_RELATION_TYPE:
    suffix = '_singlerel'
elif concept_changes == RANDOM_FEATURES:
    suffix = '_randomfeat'
else:
    suffix = ''
    
FILE_EDGES = f'{prefix}_{dataset_prefix}_kg_edges_{date_str}.csv'
FILE_NODES = f'{prefix}_{dataset_prefix}_kg_nodes_{date_str}.csv'

# Load Edges

Load all edges of knowledge graph

In [3]:
edges = pd.read_csv(f'output/{FILE_EDGES}', header=0)
edges.head(10)

,id,subject,object,relation_id,relation_label,relation_iri
0,bdb92471dc3d709e85a9a48384db1082,ZFIN:ZDB-GENE-161101-1,RGD:1624211,RO:HOM0000017,in orthology relationship with,NaN
1,6c9d777225b8200b7c5018862bcd0b43,ENSEMBL:ENSGALG00000052686,RGD:735037,RO:HOM0000017,in orthology relationship with,NaN
2,418bc3a4cb8bfbcc95726c29bd4171f1,ZFIN:ZDB-GENE-040426-1975,ZFIN:ZDB-GENE-041114-105,RO:0002434,interacts with,NaN
3,b4c8c60751a5292c312dcd55a38cfa54,RGD:68337,ENSEMBL:ENSGALG00000015635,RO:HOM0000020,in 1 to 1 orthology relationship with,NaN
4,60722b0586baca6eabdd8dd95158f26b,ENSEMBL:ENSPTRG00000008480,MGI:105922,RO:HOM0000020,in 1 to 1 orthology relationship with,NaN
5,8a722735bd91e5b46ef55b0e2ebf8245,RGD:1359292,ENSEMBL:ENSMMUG00000050761,RO:HOM0000017,in orthology relationship with,NaN
6,01a6d04733fab199eeaee3bd71bbc68c,MGI:1923551,ENSEMBL:ENSMODG00000002929,RO:HOM0000020,in 1 to 1 orthology relationship with,NaN
7,78d3c8be4ee4e0520c12f354d5416de0,ENSEMBL:ENSGALG00000028749,ENSEMBL:ENSCAFG00000005734,RO:HOM0000020,in 1 to 1 orthology relationship with,NaN
8,37943ae3da5e65c8aea242908f2864b4,RGD:2174,GO:0032991,BFO:0000050,is part of,NaN
9,e0b615738ca2c289138a350b77d5da47,WormBase:WBGene00010663,WormBase:WBGene00002005,RO:0002434,interacts with,NaN

Extract the relevant columns and rename them

In [4]:
edges = edges[['subject', 'relation_label', 'object']]
edges.rename(columns={'subject': 'head', 'relation_label': 'relation', 'object': 'tail'}, inplace=True)
edges.head(10)

,head,relation,tail
0,ZFIN:ZDB-GENE-161101-1,in orthology relationship with,RGD:1624211
1,ENSEMBL:ENSGALG00000052686,in orthology relationship with,RGD:735037
2,ZFIN:ZDB-GENE-040426-1975,interacts with,ZFIN:ZDB-GENE-041114-105
3,RGD:68337,in 1 to 1 orthology relationship with,ENSEMBL:ENSGALG00000015635
4,ENSEMBL:ENSPTRG00000008480,in 1 to 1 orthology relationship with,MGI:105922
5,RGD:1359292,in orthology relationship with,ENSEMBL:ENSMMUG00000050761
6,MGI:1923551,in 1 to 1 orthology relationship with,ENSEMBL:ENSMODG00000002929
7,ENSEMBL:ENSGALG00000028749,in 1 to 1 orthology relationship with,ENSEMBL:ENSCAFG00000005734
8,RGD:2174,is part of,GO:0032991
9,WormBase:WBGene00010663,interacts with,WormBase:WBGene00002005

In [5]:
def convert_to_int_str(value):
    try:
        return str(int(float(value)))
    except ValueError:
        return value

edges['head'] = edges['head'].apply(convert_to_int_str)
edges['tail'] = edges['tail'].apply(convert_to_int_str)

In [6]:
print(f'There are {edges.shape[0]} edges')

There are 228999 edges

# Load Nodes

Load all nodes of knowledge graph

In [7]:
nodes = pd.read_csv(f'output/{FILE_NODES}', header=0)
nodes['index_id'] = nodes.index
nodes.head(10)

,id,label,iri,semantic,taxon_id,taxon_label,index_id
0,ENSEMBL:ENSMMUG00000000800,ENSEMBL:ENSMMUG00000000800,NaN,ORTH,NaN,NaN,0
1,EnsemblGenome:BAE76810,EnsemblGenome:BAE76810,NaN,ORTH,NCBITaxon:562,Escherichia coli,1
2,ZP:0019045,"cell projection Muller cell decreased amount, ...",NaN,DISO,NaN,NaN,2
3,ZP:0000563,"neutrophil decreased amount, abnormal",NaN,DISO,NaN,NaN,3
4,MP:0008260,abnormal autophagy,NaN,DISO,NaN,NaN,4
5,FBcv:0002009,lethal - all die during third instar larval stage,NaN,DISO,NaN,NaN,5
6,PomBase:SPBC405.04c,ypt7,NaN,GENO,NaN,NaN,6
7,ENSEMBL:ENSCAFG00000008828,J9PAM4,NaN,ORTH,NaN,NaN,7
8,RGD:621876,Syt12,NaN,ORTH,NCBITaxon:10116,Rattus norvegicus,8
9,ENSEMBL:ENSPTRG00000014221,ENSEMBL:ENSPTRG00000014221,NaN,ORTH,NaN,NaN,9

Extract relevant columns

In [8]:
nodes = nodes[['index_id', 'id', 'semantic', 'label']]
nodes.head(10)

,index_id,id,semantic,label
0,0,ENSEMBL:ENSMMUG00000000800,ORTH,ENSEMBL:ENSMMUG00000000800
1,1,EnsemblGenome:BAE76810,ORTH,EnsemblGenome:BAE76810
2,2,ZP:0019045,DISO,"cell projection Muller cell decreased amount, ..."
3,3,ZP:0000563,DISO,"neutrophil decreased amount, abnormal"
4,4,MP:0008260,DISO,abnormal autophagy
5,5,FBcv:0002009,DISO,lethal - all die during third instar larval stage
6,6,PomBase:SPBC405.04c,GENO,ypt7
7,7,ENSEMBL:ENSCAFG00000008828,ORTH,J9PAM4
8,8,RGD:621876,ORTH,Syt12
9,9,ENSEMBL:ENSPTRG00000014221,ORTH,ENSEMBL:ENSPTRG00000014221

In [9]:
print(f'There are {nodes.shape[0]} nodes')

There are 14833 nodes

Convert semantic groups from categorical to numerical values (`semantic_id`)

In [10]:
nodes['semantic'] = nodes['semantic'].astype('category')
nodes['semantic_id'] = nodes['semantic'].cat.codes
nodes.head(10)

,index_id,id,semantic,label,semantic_id
0,0,ENSEMBL:ENSMMUG00000000800,ORTH,ENSEMBL:ENSMMUG00000000800,5
1,1,EnsemblGenome:BAE76810,ORTH,EnsemblGenome:BAE76810,5
2,2,ZP:0019045,DISO,"cell projection Muller cell decreased amount, ...",1
3,3,ZP:0000563,DISO,"neutrophil decreased amount, abnormal",1
4,4,MP:0008260,DISO,abnormal autophagy,1
5,5,FBcv:0002009,DISO,lethal - all die during third instar larval stage,1
6,6,PomBase:SPBC405.04c,GENO,ypt7,4
7,7,ENSEMBL:ENSCAFG00000008828,ORTH,J9PAM4,5
8,8,RGD:621876,ORTH,Syt12,5
9,9,ENSEMBL:ENSPTRG00000014221,ORTH,ENSEMBL:ENSPTRG00000014221,5

Create a dictionary that can be used as mapping between `semantic_id` and `semantic`

In [11]:
node_semantic_dict = dict(enumerate(nodes['semantic'].cat.categories))
node_semantic_dict

{0: 'ANAT',
 1: 'DISO',
 2: 'DRUG',
 3: 'GENE',
 4: 'GENO',
 5: 'ORTH',
 6: 'PHYS',
 7: 'VARI'}

Save new dataframe containing all nodes into csv file

In [12]:
nodes.to_csv(f'output/indexed_nodes_{dataset_nr}{suffix}.csv', index=False)

# Joining Dataframes

Merge dataframes with nodes and edges in order to join semantic classes and indices of nodes with heads and tails of the edges.

In [13]:
kg_df = pd.merge(edges, nodes,
                 left_on='head', right_on='id',
                 how='inner')
kg_df = kg_df[['head', 'label', 'semantic_id', 'index_id', 'relation', 'tail']]
kg_df.rename(columns={'label': 'label_head', 'semantic_id': 'class_head', 'index_id': 'index_head'}, inplace=True)
kg_df.head(10)

,head,label_head,class_head,index_head,relation,tail
0,ZFIN:ZDB-GENE-161101-1,si:dkey-52p2.5,5,2310,in orthology relationship with,RGD:1624211
1,ENSEMBL:ENSGALG00000052686,MHCIA6,5,5463,in orthology relationship with,RGD:735037
2,ZFIN:ZDB-GENE-040426-1975,grb2b,5,11415,interacts with,ZFIN:ZDB-GENE-041114-105
3,RGD:68337,Htt,5,7902,in 1 to 1 orthology relationship with,ENSEMBL:ENSGALG00000015635
4,ENSEMBL:ENSPTRG00000008480,ENSEMBL:ENSPTRG00000008480,5,1769,in 1 to 1 orthology relationship with,MGI:105922
5,RGD:1359292,RT1-CE10,5,8482,in orthology relationship with,ENSEMBL:ENSMMUG00000050761
6,MGI:1923551,Trafd1,5,3406,in 1 to 1 orthology relationship with,ENSEMBL:ENSMODG00000002929
7,ENSEMBL:ENSGALG00000028749,ENSEMBL:ENSGALG00000028749,5,7780,in 1 to 1 orthology relationship with,ENSEMBL:ENSCAFG00000005734
8,RGD:2174,Atp2a2,5,11184,is part of,GO:0032991
9,WormBase:WBGene00010663,toca-2,5,12292,interacts with,WormBase:WBGene00002005

In [14]:
kg_df = pd.merge(kg_df, nodes,
                 left_on='tail', right_on='id',
                 how='left')
kg_df = kg_df[['head', 'label_head', 'class_head', 'index_head', 'relation', 'tail', 'label', 'semantic_id', 'index_id']]
kg_df.rename(columns={'label': 'label_tail', 'semantic_id': 'class_tail', 'index_id': 'index_tail'}, inplace=True)
kg_df.head(10)

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail
0,ZFIN:ZDB-GENE-161101-1,si:dkey-52p2.5,5,2310,in orthology relationship with,RGD:1624211,RT1-T24-3,5,7485
1,ENSEMBL:ENSGALG00000052686,MHCIA6,5,5463,in orthology relationship with,RGD:735037,RT1-S3,5,13801
2,ZFIN:ZDB-GENE-040426-1975,grb2b,5,11415,interacts with,ZFIN:ZDB-GENE-041114-105,trip10a,5,12716
3,RGD:68337,Htt,5,7902,in 1 to 1 orthology relationship with,ENSEMBL:ENSGALG00000015635,ENSEMBL:ENSGALG00000015635,5,487
4,ENSEMBL:ENSPTRG00000008480,ENSEMBL:ENSPTRG00000008480,5,1769,in 1 to 1 orthology relationship with,MGI:105922,Rpl13,5,12259
5,RGD:1359292,RT1-CE10,5,8482,in orthology relationship with,ENSEMBL:ENSMMUG00000050761,ENSEMBL:ENSMMUG00000050761,5,6180
6,MGI:1923551,Trafd1,5,3406,in 1 to 1 orthology relationship with,ENSEMBL:ENSMODG00000002929,ENSEMBL:ENSMODG00000002929,5,4461
7,ENSEMBL:ENSGALG00000028749,ENSEMBL:ENSGALG00000028749,5,7780,in 1 to 1 orthology relationship with,ENSEMBL:ENSCAFG00000005734,ENSEMBL:ENSCAFG00000005734,5,6249
8,RGD:2174,Atp2a2,5,11184,is part of,GO:0032991,protein-containing complex,6,7468
9,WormBase:WBGene00010663,toca-2,5,12292,interacts with,WormBase:WBGene00002005,hsp-1,5,12561

Encode string values of relation labels as numeric values.

In [15]:
kg_df['type'], relation_labels = pd.factorize(kg_df['relation'])
kg_df.head(10)

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
0,ZFIN:ZDB-GENE-161101-1,si:dkey-52p2.5,5,2310,in orthology relationship with,RGD:1624211,RT1-T24-3,5,7485,0
1,ENSEMBL:ENSGALG00000052686,MHCIA6,5,5463,in orthology relationship with,RGD:735037,RT1-S3,5,13801,0
2,ZFIN:ZDB-GENE-040426-1975,grb2b,5,11415,interacts with,ZFIN:ZDB-GENE-041114-105,trip10a,5,12716,1
3,RGD:68337,Htt,5,7902,in 1 to 1 orthology relationship with,ENSEMBL:ENSGALG00000015635,ENSEMBL:ENSGALG00000015635,5,487,2
4,ENSEMBL:ENSPTRG00000008480,ENSEMBL:ENSPTRG00000008480,5,1769,in 1 to 1 orthology relationship with,MGI:105922,Rpl13,5,12259,2
5,RGD:1359292,RT1-CE10,5,8482,in orthology relationship with,ENSEMBL:ENSMMUG00000050761,ENSEMBL:ENSMMUG00000050761,5,6180,0
6,MGI:1923551,Trafd1,5,3406,in 1 to 1 orthology relationship with,ENSEMBL:ENSMODG00000002929,ENSEMBL:ENSMODG00000002929,5,4461,2
7,ENSEMBL:ENSGALG00000028749,ENSEMBL:ENSGALG00000028749,5,7780,in 1 to 1 orthology relationship with,ENSEMBL:ENSCAFG00000005734,ENSEMBL:ENSCAFG00000005734,5,6249,2
8,RGD:2174,Atp2a2,5,11184,is part of,GO:0032991,protein-containing complex,6,7468,3
9,WormBase:WBGene00010663,toca-2,5,12292,interacts with,WormBase:WBGene00002005,hsp-1,5,12561,1

In [16]:
relation_labels

Index(['in orthology relationship with', 'interacts with',
       'in 1 to 1 orthology relationship with', 'is part of', 'enables',
       'has phenotype', 'contributes to condition', 'expressed in', 'targets',
       'involved in', 'has role in modeling', 'colocalizes with',
       'is allele of', 'is substance that treats', 'has affected feature',
       'has genotype', 'causes condition',
       'is causal germline mutation partially giving rise to',
       'pathogenic for condition', 'contributes to',
       'is causal germline mutation in'],
      dtype='object')

Save new dataframe containing all edges into csv file

In [17]:
if concept_changes == NO_GENE_PRODUCTS and dataset_nr == 2:
    all_edges = kg_df.copy()
    
    all_gene_products = all_edges.loc[all_edges['type'] == list(relation_labels).index('is product of')]
    all_targeting_drugs = all_edges.loc[all_edges['type'] == list(relation_labels).index('targets')]
    
    merged_df = pd.merge(all_targeting_drugs, all_gene_products, how='left', left_on='tail', right_on='head', indicator=True)
    result_df = merged_df[merged_df['_merge'] == 'both']
    
    new_edges = result_df[['head_x', 'label_head_x', 'class_head_x', 'index_head_x', 'relation_x', 'tail_y', 'label_tail_y', 'class_tail_y', 'index_tail_y', 'type_y']]
    drug_gene_edges = new_edges.rename(columns={'head_x': 'head', 'label_head_x': 'label_head', 'class_head_x': 'class_head', 'index_head_x': 'index_head', 
                                                'relation_x': 'relation', 'tail_y': 'tail', 'label_tail_y': 'label_tail', 'class_tail_y': 'class_tail', 'index_tail_y': 'index_tail', 'type_y': 'type'})
    
    
    all_non_gene_products = all_edges.loc[(all_edges['type'] != list(relation_labels).index('is product of')) & (all_edges['type'] != list(relation_labels).index('targets'))]
    all_new_edges = pd.concat([all_non_gene_products, drug_gene_edges], ignore_index=True)

    gene_products_nodes = nodes.loc[nodes['semantic'] == 'gene product']
    no_gene_products_nodes = nodes.loc[nodes['semantic'] != 'gene product']
    no_gene_products_nodes.reset_index(inplace=True)
    no_gene_products_nodes['index_id'] = no_gene_products_nodes.index
    
    # Remap indices of head and tail of edges with node indices
    reindexed_left = pd.merge(all_new_edges, no_gene_products_nodes, how='inner', left_on='index_head', right_on='index')[['head', 'label_head', 'class_head', 'index_id', 
                                                                                                                           'relation', 
                                                                                                                           'tail', 'label_tail', 'class_tail', 'index_tail', 'type']]
    reindexed_left.rename(columns={'index_id': 'index_head'}, inplace=True)
    reindexed_left_right = pd.merge(reindexed_left, no_gene_products_nodes, how='inner', left_on='index_tail', right_on='index')[['head', 'label_head', 'class_head', 'index_head', 
                                                                                                                                  'relation', 
                                                                                                                                  'tail', 'label_tail', 'class_tail', 'index_id', 'type']]
    reindexed_left_right.rename(columns={'index_id': 'index_tail'}, inplace=True)
    
    no_gene_products_nodes.drop(['index'], axis=1, inplace=True)
    
    # Remap relation type indices
    reindexed_left_right['type'], relation_labels_new = pd.factorize(reindexed_left_right['relation'])
    
    # Remap node type indices
    no_gene_products_nodes['semantic_id'] = no_gene_products_nodes['semantic'].cat.codes
    
    print(f'There are {nodes.shape[0]} nodes in total before change')
    print(f'There are {no_gene_products_nodes.shape[0]} nodes after change')
    print(f'There are {gene_products_nodes.shape[0]} gene product nodes removed after change')

    print(f'There are {kg_df.shape[0]} edges in total before change')
    print(f'There are {reindexed_left_right.shape[0]} edges after change')
    print(f'There are {all_gene_products.shape[0]} gene product related rows removed after change')
    
    print(f'Changed from {len(relation_labels)} types of relations to {len(relation_labels_new)} types of relations.')
    print(f"Changed from {len(node_semantic_dict)} types of nodes to {no_gene_products_nodes['semantic_id'].nunique()} nodes.")
    
elif concept_changes == SINGLE_RELATION_TYPE:
    all_edges = kg_df.copy()
    all_edges['relation'] = 'edge'
    all_edges['type'], relation_labels_new = pd.factorize(all_edges['relation'])

    print(f'There are {kg_df.shape[0]} edges in total before change')
    print(f'There are {all_edges.shape[0]} edges after change')
    
    print(f'Changed from {len(relation_labels)} types of relations to {len(relation_labels_new)} types of relations.')
    print(f"Changed from {len(node_semantic_dict)} types of nodes to {nodes['semantic_id'].nunique()} nodes.")

In [18]:
if concept_changes == NO_GENE_PRODUCTS and dataset_nr == 2:
    reindexed_left_right.to_csv(f'output/indexed_edges_{dataset_nr}{suffix}.csv', index=False)
    no_gene_products_nodes.to_csv(f'output/indexed_nodes_{dataset_nr}{suffix}.csv', index=False)
    
elif concept_changes == SINGLE_RELATION_TYPE:
    all_edges.to_csv(f'output/indexed_edges_{dataset_nr}{suffix}.csv', index=False)
    
else:
    kg_df.to_csv(f'output/indexed_edges_{dataset_nr}{suffix}.csv', index=False)