This notebook loads all edges and nodes of the relevant knowledge graph. New dataframes are created for the nodes and edges including index values for each node.

# Import Libraries

In [19]:
import pandas as pd

# Set Parameters

Specify which dataset is used.
*   1 (Original knowledge graph)
*   2 (Restructured knowledge graph)

In [20]:
dataset_nr = 2
assert dataset_nr == 1 or 2

NO_GENE_PRODUCTS = 'no gene products'
SINGLE_RELATION_TYPE = 'only one relation type'
RANDOM_FEATURES = 'random node embedding values'
concept_changes = ''

dataset_prefix = 'hd'

if dataset_nr == 1:
    prefix = 'prev'
    date_str = '2024-07-23'
else:
    prefix = 'restr'
    date_str = '2024-07-23'
    
if concept_changes == NO_GENE_PRODUCTS:
    suffix = '_nogeneprods'
elif concept_changes == SINGLE_RELATION_TYPE:
    suffix = '_singlerel'
elif concept_changes == RANDOM_FEATURES:
    suffix = '_randomfeat'
else:
    suffix = ''
    
FILE_EDGES = f'{prefix}_{dataset_prefix}_kg_edges_{date_str}.csv'
FILE_NODES = f'{prefix}_{dataset_prefix}_kg_nodes_{date_str}.csv'

# Load Edges

Load all edges of knowledge graph

In [21]:
edges = pd.read_csv(f'output/{dataset_prefix}/{FILE_EDGES}', header=0)
edges.head(10)

,id,subject,object,relation_id,relation_label,relation_iri
0,d80459651ca0595915e415bcd920bbe9,WormBase:WBGene00006537,WBPhenotype:0000774,RO:0003303,causes condition,http://purl.obolibrary.org/obo/RO_0003303
1,4edc7ac5207592923b8a203a9a1426a7,ENSEMBL:ENSACAG00000011267,Xenbase:XB-GENE-980957,RO:HOM0000017,in orthology relationship with,http://purl.obolibrary.org/obo/RO_HOM0000017
2,f0d0506712b35f243992e93934c43980,ENSEMBL:ENSRNOG00000022407,ENSEMBL:ENSFCAG00000023548,RO:HOM0000017,in orthology relationship with,NaN
3,67cab2221603edce5a40023c3cec7464,WormBase:WBGene00000161,WormBase:WBGene00011867,RO:0002434,interacts with,NaN
4,d52ee7819ae73973faa382ba856fdf89,ZFIN:ZDB-GENE-040426-2575,ENSEMBL:ENSFCAG00000003470,RO:HOM0000017,in orthology relationship with,NaN
5,5e2d908b8ce492688d184de53fc13cd8,ENSEMBL:ENSSSCG00000009140,ENSEMBL:ENSOANG00000003663,RO:HOM0000017,in orthology relationship with,http://purl.obolibrary.org/obo/RO_HOM0000017
6,e2deb21c269fab686e7ada1eef02136e,FlyBase:FBgn0015321,ENSEMBL:ENSACAG00000011290,RO:HOM0000017,in orthology relationship with,http://purl.obolibrary.org/obo/RO_HOM0000017
7,694e64fd46897a96c85f4cf4bc432313,ENSEMBL:ENSGALG00000050637,NCBITaxon:9031,CustomRO:foundin,found in,NaN
8,6d685876d97bafe37a95a1e7f128f2f0,MGI:97441,MP:0009779,RO:0003303,causes condition,http://purl.obolibrary.org/obo/RO_0003303
9,06a500bc1d140753621981c01aab66ab,ENSEMBL:ENSRNOG00000000787,ENSEMBL:ENSCAFG00000032222,RO:HOM0000017,in orthology relationship with,NaN

Extract the relevant columns and rename them

In [22]:
edges = edges[['subject', 'relation_label', 'object']]
edges.rename(columns={'subject': 'head', 'relation_label': 'relation', 'object': 'tail'}, inplace=True)
edges.head(10)

,head,relation,tail
0,WormBase:WBGene00006537,causes condition,WBPhenotype:0000774
1,ENSEMBL:ENSACAG00000011267,in orthology relationship with,Xenbase:XB-GENE-980957
2,ENSEMBL:ENSRNOG00000022407,in orthology relationship with,ENSEMBL:ENSFCAG00000023548
3,WormBase:WBGene00000161,interacts with,WormBase:WBGene00011867
4,ZFIN:ZDB-GENE-040426-2575,in orthology relationship with,ENSEMBL:ENSFCAG00000003470
5,ENSEMBL:ENSSSCG00000009140,in orthology relationship with,ENSEMBL:ENSOANG00000003663
6,FlyBase:FBgn0015321,in orthology relationship with,ENSEMBL:ENSACAG00000011290
7,ENSEMBL:ENSGALG00000050637,found in,NCBITaxon:9031
8,MGI:97441,causes condition,MP:0009779
9,ENSEMBL:ENSRNOG00000000787,in orthology relationship with,ENSEMBL:ENSCAFG00000032222

In [23]:
def convert_to_int_str(value):
    try:
        return str(int(float(value)))
    except ValueError:
        return value

edges['head'] = edges['head'].apply(convert_to_int_str)
edges['tail'] = edges['tail'].apply(convert_to_int_str)

In [24]:
print(f'There are {edges.shape[0]} edges')

There are 230228 edges

# Load Nodes

Load all nodes of knowledge graph

In [25]:
nodes = pd.read_csv(f'output/{dataset_prefix}/{FILE_NODES}', header=0)
nodes['index_id'] = nodes.index
nodes.head(10)

,id,label,iri,semantic,index_id
0,dictyBase:DDB_G0282941,DDB0185273,NaN,gene,0
1,WBPhenotype:0001133,division axis defective,NaN,phenotype,1
2,HP:0012005,Deja vu aura,NaN,phenotype,2
3,ENSEMBL:ENSPTRG00000043959,ENSEMBL:ENSPTRG00000043959,NaN,gene,3
4,HP:0001265,Hyporeflexia,NaN,phenotype,4
5,ENSEMBL:ENSOANG00000015672,ENSEMBL:ENSOANG00000015672,NaN,gene,5
6,RGD:621353,Cltb,NaN,gene,6
7,MONARCH:APO_0000310APO_0000245,growth in exponential phase:decreased rate,NaN,phenotype,7
8,HP:0012240,Increased intramyocellular lipid droplets,NaN,phenotype,8
9,ENSEMBL:ENSECAG00000008264,ENSEMBL:ENSECAG00000008264,NaN,gene,9

Extract relevant columns

In [26]:
nodes = nodes[['index_id', 'id', 'semantic', 'label']]
nodes.head(10)

,index_id,id,semantic,label
0,0,dictyBase:DDB_G0282941,gene,DDB0185273
1,1,WBPhenotype:0001133,phenotype,division axis defective
2,2,HP:0012005,phenotype,Deja vu aura
3,3,ENSEMBL:ENSPTRG00000043959,gene,ENSEMBL:ENSPTRG00000043959
4,4,HP:0001265,phenotype,Hyporeflexia
5,5,ENSEMBL:ENSOANG00000015672,gene,ENSEMBL:ENSOANG00000015672
6,6,RGD:621353,gene,Cltb
7,7,MONARCH:APO_0000310APO_0000245,phenotype,growth in exponential phase:decreased rate
8,8,HP:0012240,phenotype,Increased intramyocellular lipid droplets
9,9,ENSEMBL:ENSECAG00000008264,gene,ENSEMBL:ENSECAG00000008264

In [27]:
print(f'There are {nodes.shape[0]} nodes')

There are 14882 nodes

Convert semantic groups from categorical to numerical values (`semantic_id`)

In [28]:
nodes['semantic'] = nodes['semantic'].astype('category')
nodes['semantic_id'] = nodes['semantic'].cat.codes
nodes.head(10)

,index_id,id,semantic,label,semantic_id
0,0,dictyBase:DDB_G0282941,gene,DDB0185273,4
1,1,WBPhenotype:0001133,phenotype,division axis defective,8
2,2,HP:0012005,phenotype,Deja vu aura,8
3,3,ENSEMBL:ENSPTRG00000043959,gene,ENSEMBL:ENSPTRG00000043959,4
4,4,HP:0001265,phenotype,Hyporeflexia,8
5,5,ENSEMBL:ENSOANG00000015672,gene,ENSEMBL:ENSOANG00000015672,4
6,6,RGD:621353,gene,Cltb,4
7,7,MONARCH:APO_0000310APO_0000245,phenotype,growth in exponential phase:decreased rate,8
8,8,HP:0012240,phenotype,Increased intramyocellular lipid droplets,8
9,9,ENSEMBL:ENSECAG00000008264,gene,ENSEMBL:ENSECAG00000008264,4

Create a dictionary that can be used as mapping between `semantic_id` and `semantic`

In [29]:
node_semantic_dict = dict(enumerate(nodes['semantic'].cat.categories))
node_semantic_dict

{0: 'biological artifact',
 1: 'biological process',
 2: 'disease',
 3: 'drug',
 4: 'gene',
 5: 'gene product',
 6: 'genotype',
 7: 'molecular function',
 8: 'phenotype',
 9: 'taxon',
 10: 'variant'}

Save new dataframe containing all nodes into csv file

In [30]:
nodes.to_csv(f'output/{dataset_prefix}/indexed_nodes_{dataset_nr}{suffix}.csv', index=False)

# Joining Dataframes

Merge dataframes with nodes and edges in order to join semantic classes and indices of nodes with heads and tails of the edges.

In [31]:
kg_df = pd.merge(edges, nodes,
                 left_on='head', right_on='id',
                 how='inner')
kg_df = kg_df[['head', 'label', 'semantic_id', 'index_id', 'relation', 'tail']]
kg_df.rename(columns={'label': 'label_head', 'semantic_id': 'class_head', 'index_id': 'index_head'}, inplace=True)
kg_df.head(10)

,head,label_head,class_head,index_head,relation,tail
0,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0000774
1,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0002188
2,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001224
3,WormBase:WBGene00006537,tbb-2,4,10272,in orthology relationship with,MGI:107812
4,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001100
5,WormBase:WBGene00006537,tbb-2,4,10272,in orthology relationship with,ENSEMBL:ENSSSCG00000001379
6,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001102
7,WormBase:WBGene00006537,tbb-2,4,10272,interacts with,WormBase:WBGene00006533
8,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001037
9,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,ZP:0017152

In [32]:
kg_df = pd.merge(kg_df, nodes,
                 left_on='tail', right_on='id',
                 how='left')
kg_df = kg_df[['head', 'label_head', 'class_head', 'index_head', 'relation', 'tail', 'label', 'semantic_id', 'index_id']]
kg_df.rename(columns={'label': 'label_tail', 'semantic_id': 'class_tail', 'index_id': 'index_tail'}, inplace=True)
kg_df.head(10)

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail
0,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0000774,gametogenesis variant,8,9968
1,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0002188,male somatic gonad development variant,8,3292
2,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001224,axon outgrowth variant,8,8349
3,WormBase:WBGene00006537,tbb-2,4,10272,in orthology relationship with,MGI:107812,Tubb5,4,4998
4,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001100,early embryonic lethal,8,6541
5,WormBase:WBGene00006537,tbb-2,4,10272,in orthology relationship with,ENSEMBL:ENSSSCG00000001379,ENSEMBL:ENSSSCG00000001379,4,13971
6,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001102,mitotic spindle defective early emb,8,6832
7,WormBase:WBGene00006537,tbb-2,4,10272,interacts with,WormBase:WBGene00006533,tba-7,4,3902
8,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001037,sterile progeny,8,11086
9,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,ZP:0017152,"germ cell development process quality, abnormal",8,5981

Encode string values of relation labels as numeric values.

In [33]:
kg_df['type'], relation_labels = pd.factorize(kg_df['relation'])
kg_df.head(10)

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
0,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0000774,gametogenesis variant,8,9968,0
1,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0002188,male somatic gonad development variant,8,3292,0
2,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001224,axon outgrowth variant,8,8349,0
3,WormBase:WBGene00006537,tbb-2,4,10272,in orthology relationship with,MGI:107812,Tubb5,4,4998,1
4,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001100,early embryonic lethal,8,6541,0
5,WormBase:WBGene00006537,tbb-2,4,10272,in orthology relationship with,ENSEMBL:ENSSSCG00000001379,ENSEMBL:ENSSSCG00000001379,4,13971,1
6,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001102,mitotic spindle defective early emb,8,6832,0
7,WormBase:WBGene00006537,tbb-2,4,10272,interacts with,WormBase:WBGene00006533,tba-7,4,3902,2
8,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001037,sterile progeny,8,11086,0
9,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,ZP:0017152,"germ cell development process quality, abnormal",8,5981,0

In [34]:
relation_labels

Index(['causes condition', 'in orthology relationship with', 'interacts with',
       'enables', 'found in', 'contributes to condition', 'colocalizes with',
       'has role in modeling', 'expresses gene', 'is variant in',
       'involved in', 'is product of', 'targets', 'is of', 'is allele of',
       'has affected feature', 'associated with phenotype', 'has genotype',
       'is substance that treats'],
      dtype='object')

Save new dataframe containing all edges into csv file

In [35]:
if concept_changes == NO_GENE_PRODUCTS and dataset_nr == 2:
    all_edges = kg_df.copy()
    
    all_gene_products = all_edges.loc[all_edges['type'] == list(relation_labels).index('is product of')]
    all_targeting_drugs = all_edges.loc[all_edges['type'] == list(relation_labels).index('targets')]
    
    merged_df = pd.merge(all_targeting_drugs, all_gene_products, how='left', left_on='tail', right_on='head', indicator=True)
    result_df = merged_df[merged_df['_merge'] == 'both']
    
    new_edges = result_df[['head_x', 'label_head_x', 'class_head_x', 'index_head_x', 'relation_x', 'tail_y', 'label_tail_y', 'class_tail_y', 'index_tail_y', 'type_y']]
    drug_gene_edges = new_edges.rename(columns={'head_x': 'head', 'label_head_x': 'label_head', 'class_head_x': 'class_head', 'index_head_x': 'index_head', 
                                                'relation_x': 'relation', 'tail_y': 'tail', 'label_tail_y': 'label_tail', 'class_tail_y': 'class_tail', 'index_tail_y': 'index_tail', 'type_y': 'type'})
    
    
    all_non_gene_products = all_edges.loc[(all_edges['type'] != list(relation_labels).index('is product of')) & (all_edges['type'] != list(relation_labels).index('targets'))]
    all_new_edges = pd.concat([all_non_gene_products, drug_gene_edges], ignore_index=True)

    gene_products_nodes = nodes.loc[nodes['semantic'] == 'gene product']
    no_gene_products_nodes = nodes.loc[nodes['semantic'] != 'gene product']
    no_gene_products_nodes.reset_index(inplace=True)
    no_gene_products_nodes['index_id'] = no_gene_products_nodes.index
    
    # Remap indices of head and tail of edges with node indices
    reindexed_left = pd.merge(all_new_edges, no_gene_products_nodes, how='inner', left_on='index_head', right_on='index')[['head', 'label_head', 'class_head', 'index_id', 
                                                                                                                           'relation', 
                                                                                                                           'tail', 'label_tail', 'class_tail', 'index_tail', 'type']]
    reindexed_left.rename(columns={'index_id': 'index_head'}, inplace=True)
    reindexed_left_right = pd.merge(reindexed_left, no_gene_products_nodes, how='inner', left_on='index_tail', right_on='index')[['head', 'label_head', 'class_head', 'index_head', 
                                                                                                                                  'relation', 
                                                                                                                                  'tail', 'label_tail', 'class_tail', 'index_id', 'type']]
    reindexed_left_right.rename(columns={'index_id': 'index_tail'}, inplace=True)
    
    no_gene_products_nodes.drop(['index'], axis=1, inplace=True)
    
    # Remap relation type indices
    reindexed_left_right['type'], relation_labels_new = pd.factorize(reindexed_left_right['relation'])
    
    # Remap node type indices
    no_gene_products_nodes['semantic_id'] = no_gene_products_nodes['semantic'].cat.codes
    
    print(f'There are {nodes.shape[0]} nodes in total before change')
    print(f'There are {no_gene_products_nodes.shape[0]} nodes after change')
    print(f'There are {gene_products_nodes.shape[0]} gene product nodes removed after change')

    print(f'There are {kg_df.shape[0]} edges in total before change')
    print(f'There are {reindexed_left_right.shape[0]} edges after change')
    print(f'There are {all_gene_products.shape[0]} gene product related rows removed after change')
    
    print(f'Changed from {len(relation_labels)} types of relations to {len(relation_labels_new)} types of relations.')
    print(f"Changed from {len(node_semantic_dict)} types of nodes to {no_gene_products_nodes['semantic_id'].nunique()} nodes.")
    
elif concept_changes == SINGLE_RELATION_TYPE:
    all_edges = kg_df.copy()
    all_edges['relation'] = 'edge'
    all_edges['type'], relation_labels_new = pd.factorize(all_edges['relation'])

    print(f'There are {kg_df.shape[0]} edges in total before change')
    print(f'There are {all_edges.shape[0]} edges after change')
    
    print(f'Changed from {len(relation_labels)} types of relations to {len(relation_labels_new)} types of relations.')
    print(f"Changed from {len(node_semantic_dict)} types of nodes to {nodes['semantic_id'].nunique()} nodes.")

In [36]:
if concept_changes == NO_GENE_PRODUCTS and dataset_nr == 2:
    reindexed_left_right.to_csv(f'output/{dataset_prefix}/indexed_edges_{dataset_nr}{suffix}.csv', index=False)
    no_gene_products_nodes.to_csv(f'output/{dataset_prefix}/indexed_nodes_{dataset_nr}{suffix}.csv', index=False)
    
elif concept_changes == SINGLE_RELATION_TYPE:
    all_edges.to_csv(f'output/{dataset_prefix}/indexed_edges_{dataset_nr}{suffix}.csv', index=False)
    
else:
    kg_df.to_csv(f'output/{dataset_prefix}/indexed_edges_{dataset_nr}{suffix}.csv', index=False)