Merge all fetched datasets originating from Monarch Initiative, TTD and DrugCentral.

Adapted by Rosa Zwart from Jupyter Notebooks found at https://github.com/PPerdomoQ/rare-disease-explainer

In [2]:
import pandas as pd
import numpy as np

import util.constants as constants
import util.common as common

In [25]:
PREFIX_DATASET = 'hd'

#### **Format TTD data**

Save a list of all associations between DRUG and GENE in a csv file.

In [26]:
drug_targets = pd.read_csv('prev/drug.target.final.ELA.csv')
drug_targets

,DRUG_NAME,STRUCT_ID,TARGET_NAME,TARGET_CLASS,ACCESSION,GENE,SWISSPROT,ACT_VALUE,ACT_UNIT,ACT_TYPE,...,ACT_SOURCE,RELATION,MOA,MOA_SOURCE,ACT_SOURCE_URL,MOA_SOURCE_URL,ACTION_TYPE,TDL,ORGANISM,NEW_ID
0,adenosine,90,Glyceraldehyde-3-phosphate dehydrogenase liver,Enzyme,P04406,GAPDH,G3P_HUMAN,4.460,NaN,IC50,...,CHEMBL,=,NaN,NaN,NaN,NaN,NaN,Tchem,Homo sapiens,HGNC:4141
1,adenosine triphosphate,91,Heat shock cognate 71 kDa protein,Unclassified,P11142,HSPA8,HSP7C_HUMAN,4.760,NaN,IC50,...,CHEMBL,=,NaN,NaN,NaN,NaN,NaN,Tchem,Homo sapiens,HGNC:5241
2,adenosine triphosphate,91,Heat shock 70 kDa protein 1A,Unclassified,P0DMV8,HSPA1A,HS71A_HUMAN,5.470,NaN,IC50,...,CHEMBL,=,NaN,NaN,NaN,NaN,NaN,Tchem,Homo sapiens,HGNC:5232
3,alfentanil,114,Mu-type opioid receptor,GPCR,P35372,OPRM1,OPRM_HUMAN,8.500,NaN,EC50,...,WOMBAT-PK,=,1.0,CHEMBL,NaN,https://www.ebi.ac.uk/chembl/compound/inspect/...,AGONIST,Tclin,Homo sapiens,HGNC:8156
4,alvimopan,143,Mu-type opioid receptor,GPCR,P35372,OPRM1,OPRM_HUMAN,9.398,NaN,Ki,...,WOMBAT-PK,=,1.0,CHEMBL,NaN,https://www.ebi.ac.uk/chembl/compound/inspect/...,ANTAGONIST,Tclin,Homo sapiens,HGNC:8156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,selumetinib,5388,Epidermal growth factor receptor,Kinase,P00533,EGFR,EGFR_HUMAN,5.660,NaN,Kd,...,CHEMBL,=,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens,HGNC:3236
312,tucatinib,5389,Epidermal growth factor receptor,Kinase,P00533,EGFR,EGFR_HUMAN,6.350,NaN,IC50,...,IUPHAR,=,NaN,NaN,NaN,NaN,INHIBITOR,Tclin,Homo sapiens,HGNC:3236
313,oliceridine,5406,Mu-type opioid receptor,GPCR,P35372,OPRM1,OPRM_HUMAN,8.220,NaN,Ki,...,DRUG LABEL,=,1.0,DRUG LABEL,https://www.accessdata.fda.gov/drugsatfda_docs...,https://www.accessdata.fda.gov/drugsatfda_docs...,AGONIST,Tclin,Homo sapiens,HGNC:8156
314,trilaciclib,5442,Cyclin-dependent-like kinase 5,Kinase,Q00535,CDK5,CDK5_HUMAN,5.830,NaN,IC50,...,DRUG LABEL,=,NaN,NaN,https://www.accessdata.fda.gov/drugsatfda_docs...,NaN,INHIBITOR,Tchem,Homo sapiens,HGNC:1774
315,samidorphan,5460,Mu-type opioid receptor,GPCR,P35372,OPRM1,OPRM_HUMAN,10.280,NaN,Ki,...,DRUG LABEL,=,NaN,NaN,https://www.accessdata.fda.gov/drugsatfda_docs...,NaN,ANTAGONIST,Tclin,Homo sapiens,HGNC:8156

Get columns that are relevant.

In [27]:
drug_targets_values = drug_targets.copy()[['STRUCT_ID', 'DRUG_NAME', 'NEW_ID']]
drug_targets_values

     STRUCT_ID               DRUG_NAME     NEW_ID
0           90               adenosine  HGNC:4141
1           91  adenosine triphosphate  HGNC:5241
2           91  adenosine triphosphate  HGNC:5232
3          114              alfentanil  HGNC:8156
4          143               alvimopan  HGNC:8156
..         ...                     ...        ...
311       5388             selumetinib  HGNC:3236
312       5389               tucatinib  HGNC:3236
313       5406             oliceridine  HGNC:8156
314       5442             trilaciclib  HGNC:1774
315       5460             samidorphan  HGNC:8156

[316 rows x 3 columns]

In [28]:
drug_targets_values.drop_duplicates(inplace=True)
drug_targets_values.shape[0]

305

Add new columns that are needed to be included in the dataframe.

In [29]:
dict_list = []

for i, row in drug_targets_values.iterrows():
    tuple_dict = {
        'id': f'TTD{i}',
        'subject_id': str(row['STRUCT_ID']),
        'subject_label': row['DRUG_NAME'],
        'subject_iri': np.nan,
        'subject_category': 'DRUG',
        'subject_taxon_id': np.nan,
        'subject_taxon_label': np.nan,
        'object_id': row['NEW_ID'],
        'object_label': np.nan,
        'object_iri': np.nan,
        'object_category': np.nan,
        'object_taxon_id': np.nan,
        'object_taxon_label': np.nan,
        'relation_id': 'CustomRO:TTD',
        'relation_label': 'targets',
        'relation_iri': np.nan
    }

    dict_list.append(tuple_dict)

drugtarget_associations_df = pd.DataFrame.from_dict(dict_list)

In [30]:
drugtarget_associations_df

,id,subject_id,subject_label,subject_iri,subject_category,subject_taxon_id,subject_taxon_label,object_id,object_label,object_iri,object_category,object_taxon_id,object_taxon_label,relation_id,relation_label,relation_iri
0,TTD0,90,adenosine,NaN,DRUG,NaN,NaN,HGNC:4141,NaN,NaN,NaN,NaN,NaN,CustomRO:TTD,targets,NaN
1,TTD1,91,adenosine triphosphate,NaN,DRUG,NaN,NaN,HGNC:5241,NaN,NaN,NaN,NaN,NaN,CustomRO:TTD,targets,NaN
2,TTD2,91,adenosine triphosphate,NaN,DRUG,NaN,NaN,HGNC:5232,NaN,NaN,NaN,NaN,NaN,CustomRO:TTD,targets,NaN
3,TTD3,114,alfentanil,NaN,DRUG,NaN,NaN,HGNC:8156,NaN,NaN,NaN,NaN,NaN,CustomRO:TTD,targets,NaN
4,TTD4,143,alvimopan,NaN,DRUG,NaN,NaN,HGNC:8156,NaN,NaN,NaN,NaN,NaN,CustomRO:TTD,targets,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,TTD311,5388,selumetinib,NaN,DRUG,NaN,NaN,HGNC:3236,NaN,NaN,NaN,NaN,NaN,CustomRO:TTD,targets,NaN
301,TTD312,5389,tucatinib,NaN,DRUG,NaN,NaN,HGNC:3236,NaN,NaN,NaN,NaN,NaN,CustomRO:TTD,targets,NaN
302,TTD313,5406,oliceridine,NaN,DRUG,NaN,NaN,HGNC:8156,NaN,NaN,NaN,NaN,NaN,CustomRO:TTD,targets,NaN
303,TTD314,5442,trilaciclib,NaN,DRUG,NaN,NaN,HGNC:1774,NaN,NaN,NaN,NaN,NaN,CustomRO:TTD,targets,NaN
304,TTD315,5460,samidorphan,NaN,DRUG,NaN,NaN,HGNC:8156,NaN,NaN,NaN,NaN,NaN,CustomRO:TTD,targets,NaN

In [31]:
drugtarget_associations_df.to_csv(f'{constants.OUTPUT_FOLDER}/prev_{PREFIX_DATASET}_ttd_associations_{common.today}.csv', index=None)

#### **Format DrugCentral data**

In [32]:
drug_diseases = pd.read_csv('prev/drug_to_disease_final_v2_ELA.csv')
drug_diseases

,Unnamed: 0,DRUG_ID,DRUG_NAME,DISEASES,PHASE,Name,ontologyTermName,ontologyTermIRI,validated,review,ID
0,492,2172,Pimozide,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,False,False,HP:0100753
1,1301,91,Adenosine triphosphate,Heart disease,Phase 2,heart disease,Cardiomyopathy,http://purl.obolibrary.org/obo/HP_0001638,False,False,HP:0001638
2,1302,91,Adenosine triphosphate,Bradycardia,Discontinued in Phase 2,bradycardia,Bradycardia,http://purl.obolibrary.org/obo/HP_0001662,False,False,HP:0001662
3,2262,2351,Raloxifene,Osteoporosis,Approved,osteoporosis,Osteoporosis,http://purl.obolibrary.org/obo/HP_0000939,False,False,HP:0000939
4,2281,1990,Omeprazole,Gastroesophageal reflux disease,Approved,gastroesophageal reflux disease,Gastroesophageal reflux,http://purl.obolibrary.org/obo/HP_0002020,False,False,HP:0002020
5,2356,621,Chlorpromazine,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,False,False,HP:0100753
6,3652,725,Codeine,Cough,Phase 1,cough,Cough,http://purl.obolibrary.org/obo/HP_0012735,False,False,HP:0012735
7,4664,578,Cerulenin,Weight loss,Approved,weight loss,Weight loss,http://purl.obolibrary.org/obo/HP_0001824,False,False,HP:0001824
8,5972,1200,Flunarizine,Migraine,Approved,migraine,Migraine,http://purl.obolibrary.org/obo/HP_0002076,False,False,HP:0002076
9,6768,1989,Omapatrilat,Hypertension,Terminated,hypertension,Hypertension,http://purl.obolibrary.org/obo/HP_0000822,False,False,HP:0000822
10,7027,434,Buprenorphine,Psychiatric disorder,Phase 3,psychiatric disorder,Behavioral abnormality,http://purl.obolibrary.org/obo/HP_0000708,False,False,HP:0000708
11,7028,434,Buprenorphine,Migraine,Phase 2,migraine,Migraine,http://purl.obolibrary.org/obo/HP_0002076,False,False,HP:0002076
12,12007,1353,Haloperidol,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,False,False,HP:0100753
13,12748,1762,Methyldopa,Hypertension,Approved,hypertension,Hypertension,http://purl.obolibrary.org/obo/HP_0000822,False,False,HP:0000822
14,13453,2080,Penfluridol,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,False,False,HP:0100753
15,13486,1599,Loperamide,Diarrhea,Approved,diarrhea,Diarrhea,http://purl.obolibrary.org/obo/HP_0002014,False,False,HP:0002014
16,13499,700,Clomifene,Female infertility,Approved,female infertility,Female infertility,http://purl.obolibrary.org/obo/HP_0008222,False,False,HP:0008222
17,13579,1353,Haloperidol,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,False,False,HP:0100753
18,13599,522,Carvedilol,Congestive heart failure,Approved,congestive heart failure,Congestive heart failure,http://purl.obolibrary.org/obo/HP_0001635,False,False,HP:0001635
19,13953,5382,Bempedoic acid,Familial hypercholesterolemia,Approved,familial hypercholesterolemia,Hypercholesterolemia,http://purl.obolibrary.org/obo/HP_0003124,False,False,HP:0003124
20,17354,918,Diphenoxylate,Diarrhea,Approved,diarrhea,Diarrhea,http://purl.obolibrary.org/obo/HP_0002014,False,False,HP:0002014
21,17406,2370,Reserpine,Hypertension,Approved,hypertension,Hypertension,http://purl.obolibrary.org/obo/HP_0000822,False,False,HP:0000822
22,17544,937,Dobutamine,Heart failure,Approved,heart failure,Congestive heart failure,http://purl.obolibrary.org/obo/HP_0001635,False,False,HP:0001635
23,18177,3514,Quercetin,Obesity,Approved,obesity,Obesity,http://purl.obolibrary.org/obo/HP_0001513,False,False,HP:0001513
24,18485,2817,VESNARINONE,Cardiac failure,Approved,cardiac failure,Congestive heart failure,http://purl.obolibrary.org/obo/HP_0001635,False,False,HP:0001635
25,20430,4778,Ridaforolimus,Sarcoma,Phase 3,sarcoma,Sarcoma,http://purl.obolibrary.org/obo/HP_0100242,False,False,HP:0100242
26,21288,2123,Phenelzine,Depression,Approved,depression,Depressivity,http://purl.obolibrary.org/obo/HP_0000716,False,False,HP:0000716
27,23208,1599,Loperamide,Diarrhea,Approved,diarrhea,Diarrhea,http://purl.obolibrary.org/obo/HP_0002014,False,False,HP:0002014
28,23377,2286,Promethazine,Nausea,Approved,nausea,Nausea,http://purl.obolibrary.org/obo/HP_0002018,False,False,HP:0002018
29,23394,1574,Levorphanol,Ischemic stroke,Terminated,ischemic stroke,Ischemic stroke,http://purl.obolibrary.org/obo/HP_0002140,False,False,HP:0002140
30,23558,2054,Pantoprazole,Gastroesophageal reflux disease,Approved,gastroesophageal reflux disease,Gastroesophageal reflux,http://purl.obolibrary.org/obo/HP_0002020,False,False,HP:0002020
31,23674,1996,Orlistat,Obesity,Approved,obesity,Obesity,http://purl.obolibrary.org/obo/HP_0001513,False,False,HP:0001513
32,23916,2637,Thioridazine,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,False,False,HP:0100753
33,24093,4392,Cisplatin,Osteosarcoma,Phase 2,osteosarcoma,Osteosarcoma,http://purl.obolibrary.org/obo/HP_0002669,False,False,HP:0002669
34,24723,621,Chlorpromazine,Schizophrenia,Withdrawn from market,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,False,False,HP:0100753
35,25467,522,Carvedilol,Congestive heart failure,Approved,congestive heart failure,Congestive heart failure,http://purl.obolibrary.org/obo/HP_0001635,False,False,HP:0001635
36,25825,1878,Naloxone,Respiratory depression,Phase 3,respiratory depression,Respiratory distress,http://purl.obolibrary.org/obo/HP_0002098,False,False,HP:0002098
37,25826,1878,Naloxone,Pruritus,Phase 3,pruritus,Pruritus,http://purl.obolibrary.org/obo/HP_0000989,False,False,HP:0000989
38,26992,722,Clozapine,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,False,False,HP:0100753

In [33]:
drug_diseases_values = drug_diseases.copy()[['DRUG_ID', 'ID']]
drug_diseases_values

    DRUG_ID          ID
0      2172  HP:0100753
1        91  HP:0001638
2        91  HP:0001662
3      2351  HP:0000939
4      1990  HP:0002020
5       621  HP:0100753
6       725  HP:0012735
7       578  HP:0001824
8      1200  HP:0002076
9      1989  HP:0000822
10      434  HP:0000708
11      434  HP:0002076
12     1353  HP:0100753
13     1762  HP:0000822
14     2080  HP:0100753
15     1599  HP:0002014
16      700  HP:0008222
17     1353  HP:0100753
18      522  HP:0001635
19     5382  HP:0003124
20      918  HP:0002014
21     2370  HP:0000822
22      937  HP:0001635
23     3514  HP:0001513
24     2817  HP:0001635
25     4778  HP:0100242
26     2123  HP:0000716
27     1599  HP:0002014
28     2286  HP:0002018
29     1574  HP:0002140
30     2054  HP:0002020
31     1996  HP:0001513
32     2637  HP:0100753
33     4392  HP:0002669
34      621  HP:0100753
35      522  HP:0001635
36     1878  HP:0002098
37     1878  HP:0000989
38      722  HP:0100753

In [34]:
dict_list = []

for i, row in drug_diseases_values.iterrows():
    tuple_dict = {
        'id': f'DC{i}',
        'subject_id': row['DRUG_ID'],
        'subject_label': np.nan,
        'subject_iri': np.nan,
        'subject_category': 'DRUG',
        'subject_taxon_id': np.nan,
        'subject_taxon_label': np.nan,
        'object_id': row['ID'],
        'object_label': np.nan,
        'object_iri': np.nan,
        'object_category': np.nan,
        'object_taxon_id': np.nan,
        'object_taxon_label': np.nan,
        'relation_id': 'CustomRO:DC',
        'relation_label': 'is substance that treats',
        'relation_iri': np.nan
    }

    dict_list.append(tuple_dict)

drugdiseases_associations_df = pd.DataFrame.from_dict(dict_list)

In [35]:
drugdiseases_associations_df.head(10)

,id,subject_id,subject_label,subject_iri,subject_category,subject_taxon_id,subject_taxon_label,object_id,object_label,object_iri,object_category,object_taxon_id,object_taxon_label,relation_id,relation_label,relation_iri
0,DC0,2172,NaN,NaN,DRUG,NaN,NaN,HP:0100753,NaN,NaN,NaN,NaN,NaN,CustomRO:DC,is substance that treats,NaN
1,DC1,91,NaN,NaN,DRUG,NaN,NaN,HP:0001638,NaN,NaN,NaN,NaN,NaN,CustomRO:DC,is substance that treats,NaN
2,DC2,91,NaN,NaN,DRUG,NaN,NaN,HP:0001662,NaN,NaN,NaN,NaN,NaN,CustomRO:DC,is substance that treats,NaN
3,DC3,2351,NaN,NaN,DRUG,NaN,NaN,HP:0000939,NaN,NaN,NaN,NaN,NaN,CustomRO:DC,is substance that treats,NaN
4,DC4,1990,NaN,NaN,DRUG,NaN,NaN,HP:0002020,NaN,NaN,NaN,NaN,NaN,CustomRO:DC,is substance that treats,NaN
5,DC5,621,NaN,NaN,DRUG,NaN,NaN,HP:0100753,NaN,NaN,NaN,NaN,NaN,CustomRO:DC,is substance that treats,NaN
6,DC6,725,NaN,NaN,DRUG,NaN,NaN,HP:0012735,NaN,NaN,NaN,NaN,NaN,CustomRO:DC,is substance that treats,NaN
7,DC7,578,NaN,NaN,DRUG,NaN,NaN,HP:0001824,NaN,NaN,NaN,NaN,NaN,CustomRO:DC,is substance that treats,NaN
8,DC8,1200,NaN,NaN,DRUG,NaN,NaN,HP:0002076,NaN,NaN,NaN,NaN,NaN,CustomRO:DC,is substance that treats,NaN
9,DC9,1989,NaN,NaN,DRUG,NaN,NaN,HP:0000822,NaN,NaN,NaN,NaN,NaN,CustomRO:DC,is substance that treats,NaN

In [36]:
drugdiseases_associations_df.to_csv(f'{constants.OUTPUT_FOLDER}/prev_{PREFIX_DATASET}_drugcentral_associations_{common.today}.csv', index=None)