Taken directly from https://github.com/PPerdomoQ/rare-disease-explainer

## **Import**

In [157]:
import re
import pandas as pd

## **Drug-Target Information**

### **Load Files**

Load the information from Drug Central and Monarch:

In [158]:
df = pd.read_csv('../data/drug.target.interaction.tsv', header=0, index_col=0, sep='\t')
nodes = pd.read_csv('monarch/prev_hd_monarch_nodes_2024-06-24.csv', header=0)

In [159]:
print(len(nodes))
nodes.head(5)

14618

,id,semantic_groups,name
0,ENSEMBL:ENSOANG00000050636,ORTH,ENSEMBL:ENSOANG00000050636
1,PomBase:SPAC1093.06c,GENO,dhc1
2,MP:0001901,DISO,absence of NMDA-mediated synaptic currents
3,ZP:0010084,DISO,whole organism lacks all parts of type telence...
4,Xenbase:XB-GENE-5918988,ORTH,sqstm1

In [160]:
df

,STRUCT_ID,TARGET_NAME,TARGET_CLASS,ACCESSION,GENE,SWISSPROT,ACT_VALUE,ACT_UNIT,ACT_TYPE,ACT_COMMENT,ACT_SOURCE,RELATION,MOA,MOA_SOURCE,ACT_SOURCE_URL,MOA_SOURCE_URL,ACTION_TYPE,TDL,ORGANISM
DRUG_NAME,,,,,,,,,,,,,,,,,,,
levobupivacaine,4,Potassium voltage-gated channel subfamily H me...,Ion channel,Q12809,KCNH2,KCNH2_HUMAN,4.890,NaN,IC50,Inhibition of wild-type human ERG channel expr...,CHEMBL,=,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens
levobupivacaine,4,Sodium channel protein type 1 subunit alpha,Ion channel,P35498,SCN1A,SCN1A_HUMAN,5.790,NaN,IC50,NaN,WOMBAT-PK,=,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens
levobupivacaine,4,Sodium channel protein type 4 subunit alpha,Ion channel,P35499,SCN4A,SCN4A_HUMAN,NaN,NaN,NaN,NaN,WOMBAT-PK,NaN,1.0,CHEMBL,NaN,https://www.ebi.ac.uk/chembl/compound/inspect/...,BLOCKER,Tclin,Homo sapiens
levobupivacaine,4,Prostaglandin E2 receptor EP1 subtype,GPCR,P34995,PTGER1,PE2R1_HUMAN,NaN,NaN,NaN,NaN,WOMBAT-PK,NaN,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens
levobupivacaine,4,Cytochrome P450 2D6,Enzyme,P10635,CYP2D6,CP2D6_HUMAN,6.707,NaN,IC50,"DRUGMATRIX: CYP450, 2D6 enzyme inhibition (sub...",DRUG MATRIX,=,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
samidorphan,5460,Delta-type opioid receptor,GPCR,P41143,OPRD1,OPRD_HUMAN,8.590,NaN,Ki,NaN,DRUG LABEL,=,NaN,NaN,https://www.accessdata.fda.gov/drugsatfda_docs...,NaN,PARTIAL AGONIST,Tclin,Homo sapiens
sotorasib,5461,GTPase KRas,Enzyme,P01116,KRAS,RASK_HUMAN,7.030,NaN,IC50,KRAS G12C mutation,DRUG LABEL,=,1.0,DRUG LABEL,https://www.accessdata.fda.gov/drugsatfda_docs...,https://www.accessdata.fda.gov/drugsatfda_docs...,INHIBITOR,Tchem,Homo sapiens
ibrexafungerp,5462,"Beta-1,3-glucan synthase catalytic subunit 1",Enzyme,O13428,GSC1,O13428_CANAX,8.350,NaN,IC50,"MoA - inhibits the biosynthesis of beta-(1,3)-...",SCIENTIFIC LITERATURE,=,1.0,DRUG LABEL,https://pubmed.ncbi.nlm.nih.gov/24323472,https://www.accessdata.fda.gov/drugsatfda_docs...,INHIBITOR,NaN,Candida albicans
ibrexafungerp,5462,"1,3-Beta-D-glucan-UDP glucosyltransferase",Enzyme,Q6FTN8,FKS1,Q6FTN8_CANGA,7.830,NaN,IC50,"MoA - inhibits the biosynthesis of beta-(1,3)-...",SCIENTIFIC LITERATURE,=,1.0,SCIENTIFIC LITERATURE,https://pubmed.ncbi.nlm.nih.gov/24323472,https://www.accessdata.fda.gov/drugsatfda_docs...,INHIBITOR,NaN,Candida glabrata
ibrexafungerp,5462,"1,3-Beta-D-glucan-UDP glucosyltransferase",Enzyme,P87204,FKS,P87204_ASPFM,8.970,NaN,IC50,"MoA - inhibits the biosynthesis of beta-(1,3)-...",SCIENTIFIC LITERATURE,=,1.0,SCIENTIFIC LITERATURE,https://pubmed.ncbi.nlm.nih.gov/24323472,https://www.accessdata.fda.gov/drugsatfda_docs...,INHIBITOR,NaN,Neosartorya fumigata

In [161]:
df['NEW_ID'] = ''

### **Uniprot to Monarch IDs**

Use Uniprot API to obtain new target IDs:

In [162]:
"""
    @description: This module maps UniProt accession IDs to other databases depending on taxon. 
    @source: https://www.uniprot.org/help/id_mapping
    @author: Rosa Zwart
"""

import requests
import time

RETRIES = 3
POLLING_S_INTERVAL = 5

FROM_DB = 'UniProtKB_AC-ID'
DEFAULT_TO_DB = 'Ensembl'

db_mapper = {
    'Homo sapiens': 'HGNC',
    'Rattus norvegicus': 'RGD',
    'Mus musculus': 'MGI',
    'Drosophila melanogaster': 'FlyBase',
    'Caenorhabditis elegans': 'WormBase',
    'Danio rerio': 'ZFIN',
    'Escherichia coli': 'EnsemblGenome',
    'Xenopus tropicalis': 'Xenbase',
    'Dictyostelium discoideum': 'dictyBase',
    'Saccharomyces cerevisiae S288C': 'SGD',
    'Schizosaccharomyces pombe': 'PomBase'
}

class IdMapper:
    def __init__(self, ids_to_map: list, to_db = DEFAULT_TO_DB, from_db = FROM_DB):
        self.url = 'https://rest.uniprot.org'
        self.job_id = self.submit_id_mapping(ids_to_map, to_db, from_db)

        if self.check_job_ready():
            self.results = self.get_results()
        
    def submit_id_mapping(self, id_list, to_db, from_db):
        print(f'Map to database {to_db}')
        
        data_params = {
            'from': from_db,
            'to': to_db,
            'ids': ','.join(id_list)
        }
        
        for i in range(RETRIES):
            try:  
                response = requests.post(f'{self.url}/idmapping/run', data=data_params)
                response.raise_for_status()
                return response.json()['jobId']
            except Exception as e:
                if (i < RETRIES - 1):
                    print(f'Retrying in {POLLING_S_INTERVAL}s')
                    time.sleep(POLLING_S_INTERVAL)
                    continue
                else:
                    print(f'After all attempts, request could not be submitted due to {e}')
                    return None
                
    def check_job_ready(self):
        while self.job_id:
            try:
                response = requests.get(f'{self.url}/idmapping/status/{self.job_id}')
                response.raise_for_status()
                response_values = response.json()
                if 'jobStatus' in response_values:
                    if response_values['jobStatus'] == 'RUNNING':
                        print(f'Check again after {POLLING_S_INTERVAL}s')
                        time.sleep(POLLING_S_INTERVAL)
                    
                    elif response_values['jobStatus'] == 'FINISHED':
                        print('Job is finished')
                        return True
                    
                    else:
                        print(f'Job {self.job_id} had status {response_values["jobStatus"]}, stopped checking if job is ready.')
                        return False
                elif 'results' in response_values:
                        return True
                else:
                    return False
            except Exception as e:
                print(f'Failed to check whether job is finished due to {e}, try again after {POLLING_S_INTERVAL}s...')
                time.sleep(POLLING_S_INTERVAL)
                
    def get_results(self):
        for i in range(RETRIES):
            try:  
                response = requests.get(f'{self.url}/idmapping/stream/{self.job_id}')
                response.raise_for_status()
                return response.json()['results']
            except Exception as e:
                if (i < RETRIES - 1):
                    print(f'Retrying in {POLLING_S_INTERVAL}s')
                    time.sleep(POLLING_S_INTERVAL)
                    continue
                else:
                    print(f'After all attempts, request could not be submitted due to {e}')
                    return None

In [163]:
def get_single_id(id):
    """
        Get from list of IDs split by `|`, one ID.
        :return Single ID value
    """
    split_id = id.split('|')
    if len(split_id) > 1:
        return split_id[0]
    else:
        return id

def fetch_id_mappings(entries: pd.DataFrame, map_to_db):
    """
        Get ID mappings of IDs present in given dataframe. Mappings are based on given database to which the IDs need to be mapped.
        :param entries: Dataframe containing column name `ACCESSION`
        :param map_to_db: Name of database to which the given IDs need to be mapped
    """
    if (entries.shape[0] > 0):
        id_entries_to_map = entries.copy()
        id_entries_to_map['ACCESSION'] = entries.apply(lambda row: get_single_id(row['ACCESSION']), axis=1)
        
        mapper = IdMapper(ids_to_map=id_entries_to_map['ACCESSION'].to_list(), to_db=map_to_db)
        if hasattr(mapper, 'results'):
            return mapper.results
        else:
            return []
    else:
        return []

def get_mapped_ids(drug_targets):
    """
        Get mapped IDs for all included databases.
        :param drug_targets: Dataframe that contains column name `ORGANISM` and `ACCESSION`
    """
    all_mapped_id_results = []
    all_taxon_names = list(db_mapper.keys())
    
    for taxon in all_taxon_names:
        relevant_entries = drug_targets[drug_targets['ORGANISM'].str.contains(taxon)]
        id_mappings = fetch_id_mappings(relevant_entries, db_mapper[taxon])
        all_mapped_id_results = all_mapped_id_results + id_mappings

    # Map entity ids of leftover organisms to default database
    other_relevant_entries = drug_targets[~drug_targets['ORGANISM'].isin(all_taxon_names)]
    other_id_mappings = fetch_id_mappings(other_relevant_entries, DEFAULT_TO_DB)
    all_mapped_id_results = all_mapped_id_results + other_id_mappings
                
    return all_mapped_id_results

results = get_mapped_ids(drug_targets=df)

Map to database HGNC
Map to database RGD
Map to database MGI
Map to database FlyBase
Map to database WormBase
Map to database ZFIN
Map to database EnsemblGenome
Retrying in 5s
Retrying in 5s
After all attempts, request could not be submitted due to 400 Client Error:  for url: https://rest.uniprot.org/idmapping/run
Map to database PomBase
Map to database Ensembl

In [164]:
def check_split_values(value, id_value):
    parts = value.split('|')
    return all(part == id_value for part in parts)

for mapping_result in results:
    original_id = mapping_result['from']
    new_id = mapping_result['to']
    
    df.loc[df['ACCESSION'].apply(check_split_values, id_value=original_id), 'NEW_ID'] = new_id

In [165]:
df['NEW_ID'] = df['NEW_ID'].replace('', np.nan)

In [166]:
print(f'Matched IDs to ACCESSION IDs for {len(df)} rows.')

Matched IDs to ACCESSION IDs for 19378 rows.

Drop rows that don't have a new ID:

In [167]:
df = df.dropna(subset=['NEW_ID'])

In [168]:
print(f'All found matched IDs to ACCESSION IDs for {len(df)} rows.')

All found matched IDs to ACCESSION IDs for 16141 rows.

Keep only rows whose the target is in the Monarch nodes:

In [169]:
df = df[df['NEW_ID'].isin(list(nodes['id']))]
print(f'All targets that match with Monarch nodes consisting of {len(df)} rows.')

All targets that match with Monarch nodes consisting of 316 rows.

Save the Drug-Target dataframe as .csv:

In [170]:
df.to_csv('drug.target.final.ELA.csv', encoding = 'utf-8-sig')

Create and save a dataframe containing the drug nodes:

In [171]:
df['DRUG_NAME'] = df.index
df_drugs = df[['DRUG_NAME', 'STRUCT_ID']]
df_drugs = df_drugs.drop_duplicates()
df_drugs.to_csv('drug_nodes_ELA.csv', encoding = 'utf-8-sig')

In [172]:
df_drugs.head(10)

                                     DRUG_NAME  STRUCT_ID
DRUG_NAME
adenosine                            adenosine         90
adenosine triphosphate  adenosine triphosphate         91
alfentanil                          alfentanil        114
alvimopan                            alvimopan        143
amiodarone                          amiodarone        176
amodiaquine                        amodiaquine        186
anileridine                        anileridine        220
astemizole                          astemizole        249
bacitracin                          bacitracin        281
bortezomib                          bortezomib        391

## **Drug-Disease Information**

### **Text to CSV**

If already saved, run only the cell of this section, otherwise continue:

Create a Dataframe that will contain the Drug-Disease information:

In [173]:
column_names = ["DRUG_ID", "DRUG_NAME", "DISEASES", 'PHASE']

df = pd.DataFrame(columns = column_names)

Read the .txt file downloaded from TTD and convert it into a pandas dataframe:

In [174]:
with open('../data/P1-05-Drug_disease.txt') as f:
  lines = f.readlines()[22:]

In [175]:
i = 0
id = ''
name = ''
disease = ''
phase = ''

for line in lines: 
  if line.startswith('DRUGNAME'): 
    result = re.search('\t(.*)\n', line)
    name = result.group(1)
  elif line.startswith('TTDDRUID'): 
    result = re.search('\t(.*)\n', line)
    id = result.group(1)
  elif line.startswith('INDICATI'): 
    result = re.search('\t(.*)\[', line)
    result2 = re.search('\](.*)', line)
    disease = result.group(1) 
    phase = result2.group(1) 
    df.loc[i] = [id,name,disease, phase]
    i += 1
  elif line.startswith('\n'): 
    id = ''
    name = ''
    disease = ''
    phase = ''

<>:15: SyntaxWarning: invalid escape sequence '\['
<>:16: SyntaxWarning: invalid escape sequence '\]'
<>:15: SyntaxWarning: invalid escape sequence '\['
<>:16: SyntaxWarning: invalid escape sequence '\]'
C:\Users\rzwart\AppData\Local\Temp\ipykernel_17444\1061029482.py:15: SyntaxWarning: invalid escape sequence '\['
  result = re.search('\t(.*)\[', line)
C:\Users\rzwart\AppData\Local\Temp\ipykernel_17444\1061029482.py:16: SyntaxWarning: invalid escape sequence '\]'
  result2 = re.search('\](.*)', line)

In [176]:
df

,DRUG_ID,DRUG_NAME,DISEASES,PHASE
0,D00ABE,ALD-301,Ischemia,Phase 2
1,D00ABE,ALD-301,Peripheral arterial disease,Phase 2
2,D00ABO,KW-2449,Acute myeloid leukaemia,Phase 1
3,D00ABW,Opterone,Hormone deficiency,Discontinued in Phase 1
4,D00ACC,ND1251,Depression,Discontinued in Phase 1
...,...,...,...,...
28973,DZTX12,ASC-J9,End-stage renal disease,Phase 2
28974,DZU72C,OKI 179,Solid tumour/cancer,Phase 1
28975,DZVF15,TRN-110,Attention deficit hyperactivity disorder,Clinical Trial
28976,DZW53X,GSK4069889,Non-small cell lung cancer,Phase 2
28977,DZY4R2,JNJ-74699157,Solid tumour/cancer,Phase 1

In [177]:
df.to_csv('drug_to_disease.csv', encoding = 'utf-8-sig')

Run only this cell if you have already saved the Drug-Disease interactions:

In [178]:
df = pd.read_csv('drug_to_disease.csv', header=0, index_col=0)

In [179]:
df

,DRUG_ID,DRUG_NAME,DISEASES,PHASE
0,D00ABE,ALD-301,Ischemia,Phase 2
1,D00ABE,ALD-301,Peripheral arterial disease,Phase 2
2,D00ABO,KW-2449,Acute myeloid leukaemia,Phase 1
3,D00ABW,Opterone,Hormone deficiency,Discontinued in Phase 1
4,D00ACC,ND1251,Depression,Discontinued in Phase 1
...,...,...,...,...
28973,DZTX12,ASC-J9,End-stage renal disease,Phase 2
28974,DZU72C,OKI 179,Solid tumour/cancer,Phase 1
28975,DZVF15,TRN-110,Attention deficit hyperactivity disorder,Clinical Trial
28976,DZW53X,GSK4069889,Non-small cell lung cancer,Phase 2
28977,DZY4R2,JNJ-74699157,Solid tumour/cancer,Phase 1

In [180]:
df.to_csv('drug_to_disease.csv', encoding = 'utf-8-sig')

### **Load CSVs**

Load the drug nodes (obtained from Drug Central) and the Monarch nodes:

In [181]:
graph_drugs = pd.read_csv('drug_nodes_ELA.csv', header=0)
nodes = pd.read_csv('monarch/prev_hd_monarch_nodes_2024-06-24.csv', header=0)

Get list of unique drugs and diseases:

In [182]:
graph_diseases = nodes[nodes['semantic_groups'] == 'DISO']

unique_diseases = graph_diseases['name'].unique()
unique_dis_id = graph_diseases['id'].unique()
unique_diseases = [x.lower() for x in unique_diseases]

print(f'There are {len(unique_diseases)} diseases found in Monarch nodes.')

There are 6002 diseases found in Monarch nodes.

In [184]:
unique_drugs = graph_drugs['DRUG_NAME'].unique()
unique_drugs = [x.lower() for x in unique_drugs]
print(f'There are {len(unique_drugs)} drugs found in DrugCentral entries.')

There are 215 drugs found in DrugCentral entries.

At this point you should use SORTA tool (https://sorta.molgeniscloud.org/menu/main/sorta?) to match the IDs of TTD to Human Phenotype Ontology (HPO). The file is also available in the project's Github:

In [185]:
matched = pd.read_csv('../data/matched_phenotypes.csv', header = 0, delimiter = ';')

In [186]:
matched

,Name,ontologyTermName,ontologyTermIRI,score,validated,review
0,respiratory failure,Respiratory failure,http://purl.obolibrary.org/obo/HP_0002878,100.00,False,False
1,sexual dysfunction,Male sexual dysfunction,http://purl.obolibrary.org/obo/HP_0040307,86.49,False,False
2,achondroplasia,Bronchodysplasia,http://purl.obolibrary.org/obo/HP_0006533,62.50,False,False
3,glabellar frown line,Prominent glabella,http://purl.obolibrary.org/obo/HP_0002057,59.46,False,False
4,testicular germ cell tumour,Testicular neoplasm,http://purl.obolibrary.org/obo/HP_0010788,71.11,False,False
...,...,...,...,...,...,...
1796,systemic mastocytosis,Mastocytosis,http://purl.obolibrary.org/obo/HP_0100495,77.42,False,False
1797,acute iron or aluminum toxicity,Abnormal total iron binding capacity,http://purl.obolibrary.org/obo/HP_0033212,48.15,False,False
1798,chronic inflammatory demyelinating polyneuropathy,Acute demyelinating polyneuropathy,http://purl.obolibrary.org/obo/HP_0007131,64.86,False,False
1799,aortic aneurysm,Aortic aneurysm,http://purl.obolibrary.org/obo/HP_0004942,100.00,False,False
1800,fever,Fever,http://purl.obolibrary.org/obo/HP_0001945,100.00,False,False

Select only those IDs with a score greater than 80:

In [187]:
matched = matched[matched['score'] > 80]

Create the final ID:

In [188]:
matched['ID'] = matched['ontologyTermIRI'].str.split('/obo/').str[1]

C:\Users\rzwart\AppData\Local\Temp\ipykernel_17444\1934371214.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matched['ID'] = matched['ontologyTermIRI'].str.split('/obo/').str[1]

In [189]:
new_id = []
for i in matched['ID']: 
  id = re.sub("[^0-9a-zA-Z]+", ":", i)
  new_id.append(id)
matched['ID'] = new_id

C:\Users\rzwart\AppData\Local\Temp\ipykernel_17444\2151810182.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matched['ID'] = new_id

In [190]:
matched.head(10)

,Name,ontologyTermName,ontologyTermIRI,score,validated,review,ID
0,respiratory failure,Respiratory failure,http://purl.obolibrary.org/obo/HP_0002878,100.00,False,False,HP:0002878
1,sexual dysfunction,Male sexual dysfunction,http://purl.obolibrary.org/obo/HP_0040307,86.49,False,False,HP:0040307
6,pollakiuria,Pollakisuria,http://purl.obolibrary.org/obo/HP_0100515,88.00,False,False,HP:0100515
17,dental caries,Carious teeth,http://purl.obolibrary.org/obo/HP_0000670,100.00,False,False,HP:0000670
22,hematopoietic stem cell transplantation,History of bone marrow transplant,http://purl.obolibrary.org/obo/HP_0032557,85.71,False,False,HP:0032557
25,gastritis,Gastritis,http://purl.obolibrary.org/obo/HP_0005263,100.00,False,False,HP:0005263
26,arthralgia,Arthralgia,http://purl.obolibrary.org/obo/HP_0002829,100.00,False,False,HP:0002829
27,attention deficit hyperactivity disorder,Attention deficit hyperactivity disorder,http://purl.obolibrary.org/obo/HP_0007018,100.00,False,False,HP:0007018
28,female hypogonadism,Female hypogonadism,http://purl.obolibrary.org/obo/HP_0000134,100.00,False,False,HP:0000134
29,vitamin b1 deficiency,Low levels of vitamin B1,http://purl.obolibrary.org/obo/HP_0100503,100.00,False,False,HP:0100503

In [191]:
i = 0
for index, row in df.iterrows(): 
  if row['DRUG_NAME'].lower() in unique_drugs: 
    if row['DISEASES'].lower() in unique_diseases: 
      i += 1

### **Merging**

In [192]:
modified = []
for d in df['DISEASES']: 
  new_string = re.sub("[^0-9a-zA-Z]+", " ", d)
  modified.append(new_string.lower())

In [193]:
df['Name'] = modified

In [194]:
df['Name'] = df['Name'].str.strip()
matched['Name'] = matched['Name'].str.strip()

C:\Users\rzwart\AppData\Local\Temp\ipykernel_17444\140104363.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matched['Name'] = matched['Name'].str.strip()

In [195]:
final = pd.merge(df, matched, on = 'Name', how = 'left')

In [196]:
final

,DRUG_ID,DRUG_NAME,DISEASES,PHASE,Name,ontologyTermName,ontologyTermIRI,score,validated,review,ID
0,D00ABE,ALD-301,Ischemia,Phase 2,ischemia,NaN,NaN,NaN,NaN,NaN,NaN
1,D00ABE,ALD-301,Peripheral arterial disease,Phase 2,peripheral arterial disease,Peripheral arterial stenosis,http://purl.obolibrary.org/obo/HP_0004950,100.0,False,False,HP:0004950
2,D00ABO,KW-2449,Acute myeloid leukaemia,Phase 1,acute myeloid leukaemia,Acute myeloid leukemia,http://purl.obolibrary.org/obo/HP_0004808,100.0,False,False,HP:0004808
3,D00ABW,Opterone,Hormone deficiency,Discontinued in Phase 1,hormone deficiency,NaN,NaN,NaN,NaN,NaN,NaN
4,D00ACC,ND1251,Depression,Discontinued in Phase 1,depression,Depressivity,http://purl.obolibrary.org/obo/HP_0000716,100.0,False,False,HP:0000716
...,...,...,...,...,...,...,...,...,...,...,...
29562,DZU72C,OKI 179,Solid tumour/cancer,Phase 1,solid tumour cancer,NaN,NaN,NaN,NaN,NaN,NaN
29563,DZVF15,TRN-110,Attention deficit hyperactivity disorder,Clinical Trial,attention deficit hyperactivity disorder,Attention deficit hyperactivity disorder,http://purl.obolibrary.org/obo/HP_0007018,100.0,False,False,HP:0007018
29564,DZW53X,GSK4069889,Non-small cell lung cancer,Phase 2,non small cell lung cancer,Non-small cell lung carcinoma,http://purl.obolibrary.org/obo/HP_0030358,100.0,False,False,HP:0030358
29565,DZW53X,GSK4069889,Non-small cell lung cancer,Phase 2,non small cell lung cancer,Non-small cell lung carcinoma,http://purl.obolibrary.org/obo/HP_0030358,100.0,False,False,HP:0030358
29566,DZY4R2,JNJ-74699157,Solid tumour/cancer,Phase 1,solid tumour cancer,NaN,NaN,NaN,NaN,NaN,NaN

In [197]:
final.to_csv('drug_to_disease_HP.csv', encoding = 'utf-8-sig')

### **Comparison**

In [198]:
final = pd.read_csv('drug_to_disease_HP.csv', header=0)

In [199]:
final_filtered = final[final['score'] > 80]

In [200]:
len(final_filtered)

14760

In [201]:
final_filtered

,Unnamed: 0,DRUG_ID,DRUG_NAME,DISEASES,PHASE,Name,ontologyTermName,ontologyTermIRI,score,validated,review,ID
1,1,D00ABE,ALD-301,Peripheral arterial disease,Phase 2,peripheral arterial disease,Peripheral arterial stenosis,http://purl.obolibrary.org/obo/HP_0004950,100.00,False,False,HP:0004950
2,2,D00ABO,KW-2449,Acute myeloid leukaemia,Phase 1,acute myeloid leukaemia,Acute myeloid leukemia,http://purl.obolibrary.org/obo/HP_0004808,100.00,False,False,HP:0004808
4,4,D00ACC,ND1251,Depression,Discontinued in Phase 1,depression,Depressivity,http://purl.obolibrary.org/obo/HP_0000716,100.00,False,False,HP:0000716
5,5,D00ACH,HMR-4004,Bacterial infection,Terminated,bacterial infection,Cellulitis,http://purl.obolibrary.org/obo/HP_0100658,85.71,False,False,HP:0100658
11,11,D00AHT,PRAME antigen-specific cancer immunotherapeutic,Non-small-cell lung cancer,Phase 2,non small cell lung cancer,Non-small cell lung carcinoma,http://purl.obolibrary.org/obo/HP_0030358,100.00,False,False,HP:0030358
...,...,...,...,...,...,...,...,...,...,...,...,...
29560,29560,DZTX12,ASC-J9,Thrombosis,Phase 2,thrombosis,Thrombocytosis,http://purl.obolibrary.org/obo/HP_0001894,83.33,False,False,HP:0001894
29561,29561,DZTX12,ASC-J9,End-stage renal disease,Phase 2,end stage renal disease,Stage 5 chronic kidney disease,http://purl.obolibrary.org/obo/HP_0003774,100.00,False,False,HP:0003774
29563,29563,DZVF15,TRN-110,Attention deficit hyperactivity disorder,Clinical Trial,attention deficit hyperactivity disorder,Attention deficit hyperactivity disorder,http://purl.obolibrary.org/obo/HP_0007018,100.00,False,False,HP:0007018
29564,29564,DZW53X,GSK4069889,Non-small cell lung cancer,Phase 2,non small cell lung cancer,Non-small cell lung carcinoma,http://purl.obolibrary.org/obo/HP_0030358,100.00,False,False,HP:0030358
29565,29565,DZW53X,GSK4069889,Non-small cell lung cancer,Phase 2,non small cell lung cancer,Non-small cell lung carcinoma,http://purl.obolibrary.org/obo/HP_0030358,100.00,False,False,HP:0030358

In [202]:
unique_drugs

['adenosine',
 'adenosine triphosphate',
 'alfentanil',
 'alvimopan',
 'amiodarone',
 'amodiaquine',
 'anileridine',
 'astemizole',
 'bacitracin',
 'bortezomib',
 'buprenorphine',
 'butorphanol',
 'candesartan cilexetil',
 'carmofur',
 'carvedilol',
 'cefapirin',
 'cerulenin',
 'chloroquine',
 'chlorpromazine',
 'cianidanol',
 'cinnarizine',
 'clioquinol',
 'clomifene',
 'clotrimazole',
 'clozapine',
 'codeine',
 'colchicine',
 'cycloserine',
 'cyproterone acetate',
 'dactinomycin',
 'danazol',
 'dasatinib',
 'dextropropoxyphene',
 'dezocine',
 'diacerein',
 'diethylstilbestrol',
 'difenoxin',
 'alpha-ergocryptine',
 'dihydrocodeine',
 'dihydroergocristine',
 'diphenoxylate',
 'disulfiram',
 'dobutamine',
 'docetaxel',
 'domperidone',
 'ebastine',
 'econazole',
 'edetic acid',
 'erlotinib',
 'ethinylestradiol',
 'everolimus',
 'famotidine',
 'felbamate',
 'fentanyl',
 'flunarizine',
 'fluphenazine',
 'formoterol',
 'ganciclovir',
 'gefitinib',
 'glutamic acid',
 'haloperidol',
 'hesperetin',
 'hexachlorophene',
 'hydrocodone',
 'hydromorphone',
 'ifenprodil',
 'imatinib',
 'diiodohydroxyquinoline',
 'fluostigmine',
 'ketobemidone',
 'lansoprazole',
 'lapatinib',
 'levallorphan',
 'levodopa',
 'levomethadyl acetate',
 'levorphanol',
 'loperamide',
 'memantine',
 'pethidine',
 'meptazinol',
 'methadone',
 'acetylmethadol',
 'methyldopa',
 'methylthioninium chloride',
 'naltrexone',
 'miconazole',
 'midodrine',
 'mifepristone',
 'miltefosine',
 'mitoxantrone',
 'montelukast',
 'morphine',
 'nalbuphine',
 'nalmefene',
 'nalorphine',
 'naloxone',
 'nelfinavir',
 'niclosamide',
 'octreotide',
 'omapatrilat',
 'omeprazole',
 'orlistat',
 'oxycodone',
 'oxymorphone',
 'paclitaxel',
 'pantoprazole',
 'penfluridol',
 'perhexiline',
 'phenazocine',
 'phenelzine',
 'pimozide',
 'primaquine',
 'promethazine',
 'propiram',
 'rabeprazole',
 'raloxifene',
 'remifentanil',
 'reserpine',
 'ritonavir',
 'saquinavir',
 'sirolimus',
 'sorafenib',
 'sufentanil',
 'sulfaethidole',
 'sulfasalazine',
 'suloctidil',
 'sunitinib',
 'tacrine',
 'tacrolimus',
 'tamoxifen',
 'terfenadine',
 'thioguanine',
 'thioridazine',
 'tianeptine',
 'tilidine',
 'tramadol',
 'tranylcypromine',
 'vesnarinone',
 'thiamine',
 'nicotinic acid',
 'zafirlukast',
 'zotarolimus',
 'bithionol',
 'cetrimonium',
 'diosmin',
 'flusalan',
 'pentazocine',
 'quercetin',
 'ruboxistaurin',
 'rutoside',
 'ciramadol',
 'baicalin',
 'tirilazad',
 'pazopanib',
 'gentian violet',
 'temsirolimus',
 'boceprevir',
 'telaprevir',
 'vandetanib',
 'icatibant',
 'crizotinib',
 'hydroxyprogesterone caproate',
 'ruxolitinib',
 'axitinib',
 'ingenol mebutate',
 'tapentadol',
 'florbetapir f-18',
 'flutemetamol (18f)',
 'afatinib',
 'zinc chloride',
 'bosutinib',
 'cetrimide',
 'cisplatin',
 'colistin',
 'carfilzomib',
 'diosmetin',
 'methylnaltrexone',
 'rose bengal',
 'nalfurafine',
 'sodium aurothiomalate',
 'cabozantinib',
 'thiomersal',
 'ridaforolimus',
 'ibrutinib',
 'florbetaben f18',
 'naloxegol',
 'ceritinib',
 'dexrabeprazole',
 'nintedanib',
 'lenvatinib',
 'cetuximab',
 'panitumumab',
 'eluxadoline',
 'tannic acid',
 'osimertinib',
 'ixazomib',
 'necitumumab',
 'migalastat',
 'chromic chloride',
 'icotinib',
 'olmutinib',
 'naldemedine',
 'midostaurin',
 'brigatinib',
 'neratinib',
 'copanlisib',
 'dacomitinib',
 'fedratinib',
 'brilliant blue g',
 'bempedoic acid',
 'selumetinib',
 'tucatinib',
 'oliceridine',
 'trilaciclib',
 'samidorphan']

In [203]:
column_names = ["DRUG_ID", "DRUG_NAME", "DISEASES", 'PHASE']

df = pd.DataFrame(columns = column_names)

df.head(10)

Empty DataFrame
Columns: [DRUG_ID, DRUG_NAME, DISEASES, PHASE]
Index: []

In [204]:
i = 0
for index, row in final_filtered.iterrows(): 

  if row['DRUG_NAME'].lower() not in unique_drugs or row['ID'] not in unique_dis_id:
   final_filtered = final_filtered.drop(labels = index, axis = 0)
   
len(final_filtered)

39

In [205]:
i = 0
for index, row in final_filtered.iterrows(): 
  drug = row['DRUG_NAME'].lower()
  id = graph_drugs[graph_drugs['DRUG_NAME'] == drug]['STRUCT_ID'].values[0]
  final_filtered.at[index, 'DRUG_ID'] = id
len(final_filtered)

39

In [206]:
final_filtered

,Unnamed: 0,DRUG_ID,DRUG_NAME,DISEASES,PHASE,Name,ontologyTermName,ontologyTermIRI,score,validated,review,ID
492,492,2172,Pimozide,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,100.00,False,False,HP:0100753
1301,1301,91,Adenosine triphosphate,Heart disease,Phase 2,heart disease,Cardiomyopathy,http://purl.obolibrary.org/obo/HP_0001638,81.25,False,False,HP:0001638
1302,1302,91,Adenosine triphosphate,Bradycardia,Discontinued in Phase 2,bradycardia,Bradycardia,http://purl.obolibrary.org/obo/HP_0001662,100.00,False,False,HP:0001662
2262,2262,2351,Raloxifene,Osteoporosis,Approved,osteoporosis,Osteoporosis,http://purl.obolibrary.org/obo/HP_0000939,100.00,False,False,HP:0000939
2281,2281,1990,Omeprazole,Gastroesophageal reflux disease,Approved,gastroesophageal reflux disease,Gastroesophageal reflux,http://purl.obolibrary.org/obo/HP_0002020,100.00,False,False,HP:0002020
2356,2356,621,Chlorpromazine,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,100.00,False,False,HP:0100753
3652,3652,725,Codeine,Cough,Phase 1,cough,Cough,http://purl.obolibrary.org/obo/HP_0012735,100.00,False,False,HP:0012735
4664,4664,578,Cerulenin,Weight loss,Approved,weight loss,Weight loss,http://purl.obolibrary.org/obo/HP_0001824,100.00,False,False,HP:0001824
5972,5972,1200,Flunarizine,Migraine,Approved,migraine,Migraine,http://purl.obolibrary.org/obo/HP_0002076,100.00,False,False,HP:0002076
6768,6768,1989,Omapatrilat,Hypertension,Terminated,hypertension,Hypertension,http://purl.obolibrary.org/obo/HP_0000822,100.00,False,False,HP:0000822
7027,7027,434,Buprenorphine,Psychiatric disorder,Phase 3,psychiatric disorder,Behavioral abnormality,http://purl.obolibrary.org/obo/HP_0000708,100.00,False,False,HP:0000708
7028,7028,434,Buprenorphine,Migraine,Phase 2,migraine,Migraine,http://purl.obolibrary.org/obo/HP_0002076,100.00,False,False,HP:0002076
12007,12007,1353,Haloperidol,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,100.00,False,False,HP:0100753
12748,12748,1762,Methyldopa,Hypertension,Approved,hypertension,Hypertension,http://purl.obolibrary.org/obo/HP_0000822,100.00,False,False,HP:0000822
13453,13453,2080,Penfluridol,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,100.00,False,False,HP:0100753
13486,13486,1599,Loperamide,Diarrhea,Approved,diarrhea,Diarrhea,http://purl.obolibrary.org/obo/HP_0002014,100.00,False,False,HP:0002014
13499,13499,700,Clomifene,Female infertility,Approved,female infertility,Female infertility,http://purl.obolibrary.org/obo/HP_0008222,100.00,False,False,HP:0008222
13579,13579,1353,Haloperidol,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,100.00,False,False,HP:0100753
13599,13599,522,Carvedilol,Congestive heart failure,Approved,congestive heart failure,Congestive heart failure,http://purl.obolibrary.org/obo/HP_0001635,100.00,False,False,HP:0001635
13953,13953,5382,Bempedoic acid,Familial hypercholesterolemia,Approved,familial hypercholesterolemia,Hypercholesterolemia,http://purl.obolibrary.org/obo/HP_0003124,85.71,False,False,HP:0003124
17354,17354,918,Diphenoxylate,Diarrhea,Approved,diarrhea,Diarrhea,http://purl.obolibrary.org/obo/HP_0002014,100.00,False,False,HP:0002014
17406,17406,2370,Reserpine,Hypertension,Approved,hypertension,Hypertension,http://purl.obolibrary.org/obo/HP_0000822,100.00,False,False,HP:0000822
17544,17544,937,Dobutamine,Heart failure,Approved,heart failure,Congestive heart failure,http://purl.obolibrary.org/obo/HP_0001635,100.00,False,False,HP:0001635
18177,18177,3514,Quercetin,Obesity,Approved,obesity,Obesity,http://purl.obolibrary.org/obo/HP_0001513,100.00,False,False,HP:0001513
18485,18485,2817,VESNARINONE,Cardiac failure,Approved,cardiac failure,Congestive heart failure,http://purl.obolibrary.org/obo/HP_0001635,100.00,False,False,HP:0001635
20430,20430,4778,Ridaforolimus,Sarcoma,Phase 3,sarcoma,Sarcoma,http://purl.obolibrary.org/obo/HP_0100242,100.00,False,False,HP:0100242
21288,21288,2123,Phenelzine,Depression,Approved,depression,Depressivity,http://purl.obolibrary.org/obo/HP_0000716,100.00,False,False,HP:0000716
23208,23208,1599,Loperamide,Diarrhea,Approved,diarrhea,Diarrhea,http://purl.obolibrary.org/obo/HP_0002014,100.00,False,False,HP:0002014
23377,23377,2286,Promethazine,Nausea,Approved,nausea,Nausea,http://purl.obolibrary.org/obo/HP_0002018,100.00,False,False,HP:0002018
23394,23394,1574,Levorphanol,Ischemic stroke,Terminated,ischemic stroke,Ischemic stroke,http://purl.obolibrary.org/obo/HP_0002140,100.00,False,False,HP:0002140
23558,23558,2054,Pantoprazole,Gastroesophageal reflux disease,Approved,gastroesophageal reflux disease,Gastroesophageal reflux,http://purl.obolibrary.org/obo/HP_0002020,100.00,False,False,HP:0002020
23674,23674,1996,Orlistat,Obesity,Approved,obesity,Obesity,http://purl.obolibrary.org/obo/HP_0001513,100.00,False,False,HP:0001513
23916,23916,2637,Thioridazine,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,100.00,False,False,HP:0100753
24093,24093,4392,Cisplatin,Osteosarcoma,Phase 2,osteosarcoma,Osteosarcoma,http://purl.obolibrary.org/obo/HP_0002669,100.00,False,False,HP:0002669
24723,24723,621,Chlorpromazine,Schizophrenia,Withdrawn from market,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,100.00,False,False,HP:0100753
25467,25467,522,Carvedilol,Congestive heart failure,Approved,congestive heart failure,Congestive heart failure,http://purl.obolibrary.org/obo/HP_0001635,100.00,False,False,HP:0001635
25825,25825,1878,Naloxone,Respiratory depression,Phase 3,respiratory depression,Respiratory distress,http://purl.obolibrary.org/obo/HP_0002098,82.93,False,False,HP:0002098
25826,25826,1878,Naloxone,Pruritus,Phase 3,pruritus,Pruritus,http://purl.obolibrary.org/obo/HP_0000989,100.00,False,False,HP:0000989
26992,26992,722,Clozapine,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,100.00,False,False,HP:0100753

In [207]:
final_filtered = final_filtered.drop(labels = ['Unnamed: 0', 'score'], axis =1)

In [209]:
final_filtered.head(10)

,DRUG_ID,DRUG_NAME,DISEASES,PHASE,Name,ontologyTermName,ontologyTermIRI,validated,review,ID
492,2172,Pimozide,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,False,False,HP:0100753
1301,91,Adenosine triphosphate,Heart disease,Phase 2,heart disease,Cardiomyopathy,http://purl.obolibrary.org/obo/HP_0001638,False,False,HP:0001638
1302,91,Adenosine triphosphate,Bradycardia,Discontinued in Phase 2,bradycardia,Bradycardia,http://purl.obolibrary.org/obo/HP_0001662,False,False,HP:0001662
2262,2351,Raloxifene,Osteoporosis,Approved,osteoporosis,Osteoporosis,http://purl.obolibrary.org/obo/HP_0000939,False,False,HP:0000939
2281,1990,Omeprazole,Gastroesophageal reflux disease,Approved,gastroesophageal reflux disease,Gastroesophageal reflux,http://purl.obolibrary.org/obo/HP_0002020,False,False,HP:0002020
2356,621,Chlorpromazine,Schizophrenia,Approved,schizophrenia,Schizophrenia,http://purl.obolibrary.org/obo/HP_0100753,False,False,HP:0100753
3652,725,Codeine,Cough,Phase 1,cough,Cough,http://purl.obolibrary.org/obo/HP_0012735,False,False,HP:0012735
4664,578,Cerulenin,Weight loss,Approved,weight loss,Weight loss,http://purl.obolibrary.org/obo/HP_0001824,False,False,HP:0001824
5972,1200,Flunarizine,Migraine,Approved,migraine,Migraine,http://purl.obolibrary.org/obo/HP_0002076,False,False,HP:0002076
6768,1989,Omapatrilat,Hypertension,Terminated,hypertension,Hypertension,http://purl.obolibrary.org/obo/HP_0000822,False,False,HP:0000822

In [210]:
final_filtered.to_csv('drug_to_disease_final_v2_ELA.csv', encoding = 'utf-8-sig')